### ISSUE TITLE
Run test failed under centos7-python3.7-g++5.4.0-cuda10.0

### ISSUE THREAD

**Issue by ShenDezhou** [Jittor/jittor#11]
[root@PKUDELL15 mygittor]# python -m jittor.test.test_example
[i 0321 09:05:08.817482 52 v1 __init__.py:102] Run cmd: which g++
[i 0321 09:05:08.820777 52 v1 __init__.py:102] Run cmd: /usr/local/bin/g++ --version
[i 0321 09:05:08.826433 52 __init__.py:183] Found g++(5.4.0) at /usr/local/bin/g++.
[i 0321 09:05:08.832981 52 v1 __init__.py:102] Run cmd: git branch
fatal: Not a git repository (or any of the parent directories): .git
[i 0321 09:05:08.856586 72 __init__.py:183] Found /usr/local/cuda/bin/nvcc(10.0.130) at /usr/local/cuda/bin/nvcc.
which: no gdb in (/root/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/maven/bin:/usr/local/cuda/bin:/root/bin)
[i 0321 09:05:08.869479 72 __init__.py:183] Found addr2line(2.23.52) at /usr/bin/addr2line.
[i 0321 09:05:08.923038 72 compiler.py:802] pybind_include: -I/root/anaconda3/include/python3.7m -I/root/anaconda3/lib/python3.7/site-packages/pybind11-2.4.dev4-py3.7.egg/pybind11/include
[i 0321 09:05:08.950114 72 compiler.py:804] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: /root/.cache/jittor/default/g++/ee002b49b2fd09c70af20f5067a1667dcd07ec05-g++-cuda.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: 错误的值
collect2: 错误：ld 返回 1
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/__init__.py", line 10, in <module>
    from . import compiler
  File "/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/compiler.py", line 906, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/compiler.py", line 81, in compile
    return do_compile(cmd)
  File "/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/compiler.py", line 43, in do_compile
    return jit_utils.cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0321 09:05:09.531569 72 log.cc:288] Check failed ret(256) == 0(0) Something wrong ... Could you please report this issue?
 Run cmd failed: cd /root/.cache/jittor/default/g++ && /usr/local/bin/g++ /root/.cache/jittor/default/g++/obj_files/op_register.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_core.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_fetcher.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_graph.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_init.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_op_compiler.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_hash.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_nano_string.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_nano_vector.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_profiler.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_jit_flags.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_jit_tests.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_jit_op_maker.cc.o /root/.cache/jittor/default/g++/obj_files/pyjt_all.cc.o /root/.cache/jittor/default/g++/obj_files/op_utils.cc.o /root/.cache/jittor/default/g++/obj_files/event_queue.cc.o /root/.cache/jittor/default/g++/obj_files/sfrl_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/allocator.cc.o /root/.cache/jittor/default/g++/obj_files/fused_op.cc.o /root/.cache/jittor/default/g++/obj_files/fuser.cc.o /root/.cache/jittor/default/g++/obj_files/grad.cc.o /root/.cache/jittor/default/g++/obj_files/graph.cc.o /root/.cache/jittor/default/g++/obj_files/init.cc.o /root/.cache/jittor/default/g++/obj_files/jit_compiler.cc.o /root/.cache/jittor/default/g++/obj_files/jit_key.cc.o /root/.cache/jittor/default/g++/obj_files/op.cc.o /root/.cache/jittor/default/g++/obj_files/op_compiler.cc.o /root/.cache/jittor/default/g++/obj_files/var.cc.o /root/.cache/jittor/default/g++/obj_files/var_holder.cc.o /root/.cache/jittor/default/g++/obj_files/aligned_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/cuda_device_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/cuda_dual_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/cuda_host_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/cuda_managed_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/nfef_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/stat_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/cpu_atomic.cc.o /root/.cache/jittor/default/g++/obj_files/cuda_flags.cc.o /root/.cache/jittor/default/g++/obj_files/nano_string.cc.o /root/.cache/jittor/default/g++/obj_files/arg_reduce_op.cc.o /root/.cache/jittor/default/g++/obj_files/argsort_op.cc.o /root/.cache/jittor/default/g++/obj_files/array_op.cc.o /root/.cache/jittor/default/g++/obj_files/binary_op.cc.o /root/.cache/jittor/default/g++/obj_files/broadcast_to_op.cc.o /root/.cache/jittor/default/g++/obj_files/candidate_op.cc.o /root/.cache/jittor/default/g++/obj_files/clone_op.cc.o /root/.cache/jittor/default/g++/obj_files/code_op.cc.o /root/.cache/jittor/default/g++/obj_files/concat_op.cc.o /root/.cache/jittor/default/g++/obj_files/index_op.cc.o /root/.cache/jittor/default/g++/obj_files/random_op.cc.o /root/.cache/jittor/default/g++/obj_files/reduce_op.cc.o /root/.cache/jittor/default/g++/obj_files/reindex_op.cc.o /root/.cache/jittor/default/g++/obj_files/reindex_reduce_op.cc.o /root/.cache/jittor/default/g++/obj_files/reshape_op.cc.o /root/.cache/jittor/default/g++/obj_files/ternary_op.cc.o /root/.cache/jittor/default/g++/obj_files/transpose_op.cc.o /root/.cache/jittor/default/g++/obj_files/unary_op.cc.o /root/.cache/jittor/default/g++/obj_files/where_op.cc.o /root/.cache/jittor/default/g++/obj_files/expr.cc.o /root/.cache/jittor/default/g++/obj_files/jit_searcher.cc.o /root/.cache/jittor/default/g++/obj_files/kernel_ir.cc.o /root/.cache/jittor/default/g++/obj_files/pass_manager.cc.o /root/.cache/jittor/default/g++/obj_files/tuner_manager.cc.o /root/.cache/jittor/default/g++/obj_files/var_relay.cc.o /root/.cache/jittor/default/g++/obj_files/assume_aligned_pass.cc.o /root/.cache/jittor/default/g++/obj_files/atomic_tuner_pass.cc.o /root/.cache/jittor/default/g++/obj_files/check_cache_pass.cc.o /root/.cache/jittor/default/g++/obj_files/compile_shapes_pass.cc.o /root/.cache/jittor/default/g++/obj_files/expand_empty_block_pass.cc.o /root/.cache/jittor/default/g++/obj_files/fake_main_pass.cc.o /root/.cache/jittor/default/g++/obj_files/float_atomic_fix_pass.cc.o /root/.cache/jittor/default/g++/obj_files/insert_profile_loop_pass.cc.o /root/.cache/jittor/default/g++/obj_files/loop_to_func_pass.cc.o /root/.cache/jittor/default/g++/obj_files/loop_var_analyze_pass.cc.o /root/.cache/jittor/default/g++/obj_files/mark_raw_pass.cc.o /root/.cache/jittor/default/g++/obj_files/merge_loop_pass.cc.o /root/.cache/jittor/default/g++/obj_files/parallel_pass.cc.o /root/.cache/jittor/default/g++/obj_files/pass.cc.o /root/.cache/jittor/default/g++/obj_files/remove_intermediate_pass.cc.o /root/.cache/jittor/default/g++/obj_files/remove_loop_pass.cc.o /root/.cache/jittor/default/g++/obj_files/rename_loop_index_pass.cc.o /root/.cache/jittor/default/g++/obj_files/reorder_loop_pass.cc.o /root/.cache/jittor/default/g++/obj_files/replace_for_num_pass.cc.o /root/.cache/jittor/default/g++/obj_files/restride_pass.cc.o /root/.cache/jittor/default/g++/obj_files/solve_conflict_define_pass.cc.o /root/.cache/jittor/default/g++/obj_files/split_loop_pass.cc.o /root/.cache/jittor/default/g++/obj_files/unroll_pass.cc.o /root/.cache/jittor/default/g++/obj_files/use_movnt_pass.cc.o /root/.cache/jittor/default/g++/obj_files/vectorize_pass.cc.o /root/.cache/jittor/default/g++/obj_files/broadcast_tuner.cc.o /root/.cache/jittor/default/g++/obj_files/conv_tuner.cc.o /root/.cache/jittor/default/g++/obj_files/matmul_tuner.cc.o /root/.cache/jittor/default/g++/obj_files/reduce_tuner.cc.o /root/.cache/jittor/default/g++/obj_files/reorder_tuner.cc.o /root/.cache/jittor/default/g++/obj_files/tuner.cc.o /root/.cache/jittor/default/g++/obj_files/cache_info.cc.o /root/.cache/jittor/default/g++/obj_files/memory_checker.cc.o /root/.cache/jittor/default/g++/obj_files/replacement.cc.o /root/.cache/jittor/default/g++/obj_files/vtop.cc.o /root/.cache/jittor/default/g++/obj_files/core.cc.o /root/.cache/jittor/default/g++/obj_files/py_var_tracer.cc.o /root/.cache/jittor/default/g++/obj_files/numpy.cc.o /root/.cache/jittor/default/g++/obj_files/test_expr.cc.o /root/.cache/jittor/default/g++/obj_files/test_fast_shared_ptr.cc.o /root/.cache/jittor/default/g++/obj_files/test_jit_key.cc.o /root/.cache/jittor/default/g++/obj_files/test_kernel_ir.cc.o /root/.cache/jittor/default/g++/obj_files/test_nano_vector.cc.o /root/.cache/jittor/default/g++/obj_files/test_op_compiler.cc.o /root/.cache/jittor/default/g++/obj_files/test_op_relay.cc.o /root/.cache/jittor/default/g++/obj_files/test_sfrl_allocator.cc.o /root/.cache/jittor/default/g++/obj_files/flags.cc.o /root/.cache/jittor/default/g++/obj_files/mwsr_list.cc.o /root/.cache/jittor/default/g++/obj_files/profiler.cc.o /root/.cache/jittor/default/g++/obj_files/executor.cc.o /root/.cache/jittor/default/g++/obj_files/fetcher.cc.o /root/.cache/jittor/default/g++/ee002b49b2fd09c70af20f5067a1667dcd07ec05-g++-cuda.o   -Wall -Werror -Wno-unknown-pragmas -std=c++14 -fPIC -march=native -I/root/anaconda3/include/python3.7m -I/root/anaconda3/lib/python3.7/site-packages/pybind11-2.4.dev4-py3.7.egg/pybind11/include -I/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/src  -DHAS_CUDA -I'/usr/local/cuda/include' -I'/root/anaconda3/lib/python3.7/site-packages/jittor-1.0.0-py3.7.egg/jittor/extern/cuda/inc'  -I/root/.cache/jittor/default/g++  -O2    -lstdc++ -ldl -shared  -lcudart -L'/usr/local/cuda/lib64'  -o /root/.cache/jittor/default/g++/jittor_core.cpython-37m-x86_64-linux-gnu.so

**Comment by Jittor** [comment]
Hi ShenDezhou，
Thank you for reporting the error. centos is not supported yet, we are working on it.

**Comment by Jittor** [comment]
hello, centos is now supported in jittor

**Comment by ShenDezhou** [comment]
非常棒，祝贺计图！ ---- Replied Message ***@***.***>Date05/14/2021 15:18 ***@***.***> ***@***.******@***.***>SubjectRe: [Jittor/jittor] Run test failed under centos7-python3.7-g++5.4.0-cuda10.0 (#11)
hello, centos is now supported in jittor

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Jittor/jittor/issues/11#issuecomment-841064361",
"url": "https://github.com/Jittor/jittor/issues/11#issuecomment-841064361",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
