### ISSUE TITLE
AssertionError while running test example

### ISSUE THREAD

**Issue by AerysNan** [Jittor/jittor#13]
Hi, I got an assertion error when trying to run the test example given in the manual. 
```
> python3 -m jittor.test.test_example
[i 0321 14:59:04.413733 76 v1 __init__.py:102] Run cmd: which g++
[i 0321 14:59:04.429153 76 v1 __init__.py:102] Run cmd: /usr/bin/g++ --version
[i 0321 14:59:04.444102 76 __init__.py:183] Found g++(7.5.0) at /usr/bin/g++.
[i 0321 14:59:04.448991 76 v1 __init__.py:102] Run cmd: git branch
fatal: not a git repository (or any of the parent directories): .git
[i 0321 14:59:04.473556 76 v1 __init__.py:102] Run cmd: which /usr/local/cuda/bin/nvcc
[i 0321 14:59:04.491051 76 v1 compiler.py:733] /usr/local/cuda/bin/nvcc not found.
[i 0321 14:59:04.491664 76 v1 __init__.py:102] Run cmd: which gdb
[i 0321 14:59:04.510585 76 v1 compiler.py:733] gdb not found.
[i 0321 14:59:04.511085 76 v1 __init__.py:102] Run cmd: which addr2line
[i 0321 14:59:04.527993 76 v1 __init__.py:102] Run cmd: /usr/bin/addr2line --version
[i 0321 14:59:04.546289 76 __init__.py:183] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0321 14:59:04.546897 76 v1 __init__.py:102] Run cmd: /usr/bin/python3 -m pybind11 --includes
[i 0321 14:59:04.618063 76 compiler.py:802] pybind_include: -I/usr/include/python3.7m -I/usr/local/include/python3.7 -I/root/.local/include/python3.7m
[i 0321 14:59:04.618778 76 v1 __init__.py:102] Run cmd: /usr/bin/python3-config --extension-suffix
[i 0321 14:59:04.696032 76 compiler.py:804] extension_suffix: .cpython-36m-x86_64-linux-gnu.so
[i 0321 14:59:04.696785 76 v1 __init__.py:102] Run cmd: /usr/bin/g++ /usr/local/lib/python3.7/dist-packages/jittor/src/utils/cache_compile.cc /usr/local/lib/python3.7/dist-packages/jittor/src/utils/log.cc /usr/local/lib/python3.7/dist-packages/jittor/src/utils/tracer.cc /usr/local/lib/python3.7/dist-packages/jittor/src/utils/jit_utils.cc   -Wall -Werror -Wno-unknown-pragmas -std=c++14 -fPIC -march=native -I/usr/include/python3.7m -I/usr/local/include/python3.7 -I/root/.local/include/python3.7m -I/usr/local/lib/python3.7/dist-packages/jittor/src   -O2    -lstdc++ -ldl -shared  -o /root/.cache/jittor/default/g++/jit_utils_core.cpython-36m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 10, in <module>
    from . import compiler
  File "/usr/local/lib/python3.7/dist-packages/jittor/compiler.py", line 814, in <module>
    check_cache_compile()
  File "/usr/local/lib/python3.7/dist-packages/jittor/compiler.py", line 720, in check_cache_compile
    assert jit_utils.cc
AssertionError
```

I'm using:

- Ubuntu 18.04.4 (Windows WSL)
- Python 3.7.5
- GCC 7.5.0

Any help on how to fix this problem? Many thanks : )

**Comment by Jittor** [comment]
please remove the jittor cache first `rm -rf ~/.cache/jittor`,
and run `python3.7 -m jittor.test.test_example`.
use python3.7 instead of python3.

Thanks for reporting this issue, please feel free to contact us if u have any other problems.

**Comment by AerysNan** [comment]
Problem solved, thanks a lot!
