### ISSUE TITLE
Run test failed under Ubuntu16.04-python3.7-g++5.4.1

### ISSUE THREAD

**Issue by null-id** [Jittor/jittor#159]
Similar to https://github.com/Jittor/jittor/issues/153

But my g++ is not g++10

**Comment by cxjyxxme** [comment]
Thank you for this feedback, can you please post the output of the program and your g++ version?

**Comment by null-id** [comment]
```
(jt) username@server:~/jittor-master$ python -m jittor.test.test_example
[i 1205 15:25:49.493928 72 __init__.py:249] Found g++(5.4.1) at /usr/bin/g++.
[i 1205 15:25:49.686980 72 compiler.py:839] Jittor(1.2.1.2) src: /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor
[i 1205 15:25:49.687265 72 compiler.py:840] cache_path: /home/username/.cache/jittor/default/g++
[i 1205 15:25:49.722894 72 __init__.py:249] Found /usr/local/cuda/bin/nvcc(11.0.194) at /usr/local/cuda/bin/nvcc.
[i 1205 15:25:49.921823 72 __init__.py:249] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1205 15:25:49.955994 72 __init__.py:249] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1205 15:25:50.022958 72 compiler.py:889] pybind_include: -I/home/username/anaconda3/envs/jt/include/python3.7m -I/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/pybind11/include
[i 1205 15:25:50.041784 72 compiler.py:891] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
g++: error: /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/cache_compile.cc: Not a directory
g++: error: /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/log.cc: Not a directory
g++: error: /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/tracer.cc: Not a directory
g++: error: /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/jit_utils.cc: Not a directory
Traceback (most recent call last):
  File "/home/username/anaconda3/envs/jt/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/username/anaconda3/envs/jt/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/__init__.py", line 16, in <module>
    from . import compiler
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/compiler.py", line 901, in <module>
    check_cache_compile()
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/compiler.py", line 775, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, 'jit_utils_core'+extension_suffix, True)
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/compiler.py", line 69, in compile
    return do_compile(cmd)
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/compiler.py", line 47, in do_compile
    run_cmd(cmd)
  File "/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor_utils/__init__.py", line 136, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: /usr/bin/g++ /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/cache_compile.cc /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/log.cc /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/tracer.cc /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src/utils/jit_utils.cc   -Wall -Werror -Wno-unknown-pragmas -std=c++14 -fPIC -march=native  -fdiagnostics-color=always -I/home/username/anaconda3/envs/jt/include/python3.7m -I/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/pybind11/include -I/home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/src   -O2    -lstdc++ -ldl -shared  -o /home/username/.cache/jittor/default/g++/jit_utils_core.cpython-37m-x86_64-linux-gnu.so

```

**Comment by null-id** [comment]
By the way, I don't have sudo privilege on the server to change g++ version. Is it possible to install jittor?

**Comment by cxjyxxme** [comment]
This does not seem to be a g++ problem, but a file missing caused by the failure to install jittor in anaconda.
You can try to reinstall jittor using the following command in anaconda environment.
```
python3.7 -m pip uninstall jittor
python3.7 -m pip install git+https://github.com/Jittor/jittor.git
```
If the error is still not resolved, can you please run this command and post the output in order to check the installation of jittor?
`find /home/username/anaconda3/envs/jt/lib/python3.7/site-packages/jittor/`
