### ISSUE TITLE
run test_cuda success, but failed to use jt.flags.use_cuda=1

### ISSUE THREAD

**Issue by curehabit** [Jittor/jittor#177]
I installed cuda=11.0 & cudnn8 in Debian 4.19.117(with 1 x V100), and test_cuda OK。But while using jt.flags.use_cuda=1, it was failed. 

```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    main()
  File "train.py", line 10, in main
    jt.flags.use_cuda=1
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.flags)).

Types of your inputs are:
 self   = flags,
 arg    = int,

The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)

Failed reason:[f 0201 21:46:46.675946 64 cuda_flags.cc:25] Check failed: count>0  No device found.

```

**Comment by curehabit** [comment]
May be caused by the driver version

**Comment by wangg12** [comment]
For me, the reason is that the driver is lost. Just reinstalling the driver fixes this.

**Comment by Xunius** [comment]
For me (on Manjaro Linux), the cuda is often lost after waking up from a system suspension. Restarting the system fixes this.
