### ISSUE TITLE
第一次运行出现编译错误

### ISSUE THREAD

**Issue by Jittor** [Jittor/jittor#195]
错误输出如下：
```
nohup: ignoring input
[38;5;2m[i 0407 22:17:52.321460 00 compiler.py:851] Jittor(1.2.2.58) src: /home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor[m
[38;5;2m[i 0407 22:17:52.321692 00 compiler.py:852] g++ at /usr/bin/g++[m
[38;5;2m[i 0407 22:17:52.321758 00 compiler.py:853] cache_path: /home/sdu/.cache/jittor/default/g++[m
[38;5;2m[i 0407 22:17:52.345811 00 __init__.py:257] Found /usr/local/cuda/bin/nvcc(11.1.74) at /usr/local/cuda/bin/nvcc.[m
[38;5;2m[i 0407 22:17:52.585210 00 __init__.py:257] Found gdb(8.1.0) at /usr/bin/gdb.[m
[38;5;2m[i 0407 22:17:52.619655 00 __init__.py:257] Found addr2line(2.30) at /usr/bin/addr2line.[m
[38;5;2m[i 0407 22:17:52.788465 00 compiler.py:893] pybind_include: -I/home/sdu/anaconda3/envs/txa/include/python3.7m -I/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/pybind11/include[m
[38;5;2m[i 0407 22:17:52.866153 00 compiler.py:895] extension_suffix: .cpython-37m-x86_64-linux-gnu.so[m
[38;5;2m[i 0407 22:17:54.451696 00 __init__.py:169] Total mem: 15.42GB, using 5 procs for compiling.[m
[38;5;2m[i 0407 22:17:55.222659 00 jit_compiler.cc:21] Load cc_path: /usr/bin/g++[m
[38;5;2m[i 0407 22:17:55.266967 00 init.cc:54] Found cuda archs: [][m
[38;5;2m[i 0407 22:17:55.423467 00 compile_extern.py:386] mpicc not found, distribution disabled.[m
[38;5;2m[i 0407 22:17:55.686973 00 compile_extern.py:16] found /usr/local/cuda/include/cublas.h[m
[38;5;2m[i 0407 22:17:55.687184 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so[m
[38;5;2m[i 0407 22:17:55.740583 00 compile_extern.py:16] found /usr/local/cuda/include/cudnn.h[m
[38;5;2m[i 0407 22:17:55.740770 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcudnn.so[m
[38;5;2m[i 0407 22:17:55.765390 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcudnn_ops_infer.so[m
[38;5;2m[i 0407 22:17:55.798537 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcudnn_ops_train.so[m
[38;5;2m[i 0407 22:17:55.813065 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcudnn_cnn_infer.so[m
[38;5;2m[i 0407 22:17:56.132234 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcudnn_cnn_train.so[m
[38;5;2m[i 0407 22:17:56.252479 00 compiler.py:658] handle pyjt_include/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h[m
[38;5;3m[w 0407 22:17:56.358948 00 compile_extern.py:144] CUDA found but cudnn is not loaded:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor_utils/__init__.py", line 146, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [38;5;1m[f 0407 22:17:56.315665 00 log.cc:319] Check failed: ret>=0 && ret<256  Run cmd failed: cd /home/sdu/.cache/jittor/default/g++ && /usr/bin/g++ /home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/src/cudnn_conv_test.cc  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/inc' -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc'    -Wall -Werror -Wno-unknown-pragmas -std=c++14 -fPIC -march=native  -fdiagnostics-color=always  -I/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/src -I/home/sdu/anaconda3/envs/txa/include/python3.7m -I/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/pybind11/include -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/sdu/.cache/jittor/default/g++  -O2  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc'  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/ops'  -c  -o /home/sdu/.cache/jittor/default/g++/obj_files/cudnn_conv_test.cc.o 
return -1. This might be an overcommit issue or out of memory. Try : sudo sysctl vm.overcommit_memory=1[m
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/compile_extern.py", line 140, in setup_cuda_extern
    setup_cuda_lib(lib_name)
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/compile_extern.py", line 191, in setup_cuda_lib
    extra_flags=f" -I'{jt_cuda_include}' -I'{jt_culib_include}' {link_flags} {extra_flags} ")
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/lock.py", line 32, in inner
    ret = func(*args, **kw)
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/compiler.py", line 675, in compile_custom_ops
    compile(cc_path, extra_flags+cc_flags+opt_flags+includes, builds, gen_lib)
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/compiler.py", line 90, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor_utils/__init__.py", line 178, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/home/sdu/anaconda3/envs/txa/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
RuntimeError: [38;5;1m[f 0407 22:17:56.315665 00 log.cc:319] Check failed: ret>=0 && ret<256  Run cmd failed: cd /home/sdu/.cache/jittor/default/g++ && /usr/bin/g++ /home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/src/cudnn_conv_test.cc  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/inc' -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc'    -Wall -Werror -Wno-unknown-pragmas -std=c++14 -fPIC -march=native  -fdiagnostics-color=always  -I/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/src -I/home/sdu/anaconda3/envs/txa/include/python3.7m -I/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/pybind11/include -DHAS_CUDA -I'/usr/local/cuda/include' -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/inc'  -I/home/sdu/.cache/jittor/default/g++  -O2  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc'  -I'/home/sdu/anaconda3/envs/txa/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/ops'  -c  -o /home/sdu/.cache/jittor/default/g++/obj_files/cudnn_conv_test.cc.o 
return -1. This might be an overcommit issue or out of memory. Try : sudo sysctl vm.overcommit_memory=1[m
[m
[38;5;3m[w 0407 22:17:56.359354 00 compile_extern.py:146] Develop version of CUDNN not found, please refer to CUDA offical tar file installation: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar[m
[38;5;2m[i 0407 22:17:56.359623 00 compile_extern.py:16] found /usr/local/cuda/include/curand.h[m
[38;5;2m[i 0407 22:17:56.359828 00 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so[m
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from WindowUI import WindowUI
  File "/home/sdu/lvxingming/DeepFaceDrawing-Jittor-master/WindowUI.py", line 18, in <module>
    jt.flags.use_cuda = 1
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.flags)).

Types of your inputs are:
 self	= flags,
 arg	= int,

The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)

Failed reason:[38;5;1m[f 0407 22:17:57.498035 00 cuda_flags.cc:25] Check failed: count>0  No device found.[m

```

**Comment by Jittor** [comment]
解决方法：运行命令`sudo sysctl vm.overcommit_memory=1`
