### ISSUE TITLE
初次安装编译和导包中的错误

### ISSUE THREAD

**Issue by OneIsAll-w** [Jittor/jittor#209]
import jittor
[i 0510 13:24:13.476834 36 compiler.py:851] Jittor(1.2.2.70) src: /home/tw/anaconda3/lib/python3.7/site-packages/jittor
[i 0510 13:24:13.476953 36 compiler.py:852] g++ at /usr/bin/g++
[i 0510 13:24:13.477022 36 compiler.py:853] cache_path: /home/tw/.cache/jittor/default/g++
[i 0510 13:24:13.485355 36 __init__.py:257] Found /usr/local/cuda/bin/nvcc(10.2.89) at /usr/local/cuda/bin/nvcc.
[i 0510 13:24:13.566227 36 __init__.py:257] Found gdb(8.1.1) at /usr/bin/gdb.
[i 0510 13:24:13.576473 36 __init__.py:257] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0510 13:24:13.623221 36 compiler.py:893] pybind_include: -I/home/tw/anaconda3/include/python3.7m -I/home/tw/anaconda3/lib/python3.7/site-packages/pybind11/include
[i 0510 13:24:13.648303 36 compiler.py:895] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 0510 13:24:13.863620 36 __init__.py:169] Total mem: 502.57GB, using 16 procs for compiling.
[i 0510 13:24:14.525893 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
[i 0510 13:24:14.528559 36 init.cc:54] Found cuda archs: [70,]
[i 0510 13:24:14.660948 36 compile_extern.py:386] mpicc not found, distribution disabled.
[i 0510 13:24:14.738995 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h
[w 0510 13:24:14.739871 36 compile_extern.py:144] CUDA found but cublas is not loaded:
Traceback (most recent call last):
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 140, in setup_cuda_extern
    setup_cuda_lib(lib_name)
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 165, in setup_cuda_lib
    culib_path = search_file([cuda_lib, extra_lib_path, "/usr/lib/x86_64-linux-gnu"], f"lib{lib_name}.so")
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 18, in search_file
    LOG.f(f"file {name} not found in {dirs}")
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor_utils/__init__.py", line 62, in f
    def f(self, *msg): self._log('f', 0, *msg)
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor_utils/__init__.py", line 47, in _log
    cc.log(fileline, level, verbose, msg)
RuntimeError: [f 0510 13:24:14.739239 36 compile_extern.py:18] file libcublas.so not found in ['/usr/local/cuda/lib64', '/usr/local/cuda/targets/x86_64-linux/lib', '/usr/lib/x86_64-linux-gnu']

[w 0510 13:24:14.740520 36 compile_extern.py:144] CUDA found but cudnn is not loaded:
Traceback (most recent call last):
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 140, in setup_cuda_extern
    setup_cuda_lib(lib_name)
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 164, in setup_cuda_lib
    cuda_include_name = search_file([cuda_include, extra_include_path, "/usr/include"], lib_name+".h")
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor/compile_extern.py", line 18, in search_file
    LOG.f(f"file {name} not found in {dirs}")
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor_utils/__init__.py", line 62, in f
    def f(self, *msg): self._log('f', 0, *msg)
  File "/home/tw/anaconda3/lib/python3.7/site-packages/jittor_utils/__init__.py", line 47, in _log
    cc.log(fileline, level, verbose, msg)
RuntimeError: [f 0510 13:24:14.740178 36 compile_extern.py:18] file cudnn.h not found in ['/usr/local/cuda/include', '/usr/local/cuda/targets/x86_64-linux/include', '/usr/include']

[w 0510 13:24:14.740677 36 compile_extern.py:146] Develop version of CUDNN not found, please refer to CUDA offical tar file installation: https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar
[i 0510 13:24:14.740881 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h
[i 0510 13:24:14.741015 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so

**Comment by Jittor** [comment]
您好，感谢您的反馈，jittor似乎没有找到cublas和cudnn，理论上是可以继续运行的，但是会变慢。
cudnn的安装可以参考 https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar， cublas可能需要您使用cuda run文件完整安装cuda才能解决。
后续有问题欢迎随时联系
