### ISSUE TITLE
got runtime error ...any idea

### ISSUE THREAD

**Issue by Trivenu** [Jittor/jittor#218]
on3.8 -I/home/karthik/.local/lib/python3.8/site-packages/pybind11/include
[i 0524 10:49:50.172849 52 compiler.py:898] extension_suffix: .cpython-38-x86_64-linux-gnu.so
[i 0524 10:49:50.427291 52 __init__.py:168] Total mem: 10.62GB, using 3 procs for compiling.
[i 0524 10:49:50.993130 52 jit_compiler.cc:20] Load cc_path: /usr/bin/g++
[i 0524 10:49:51.052464 52 __init__.py:249] Found mpicc(4.0.3) at /usr/bin/mpicc.
[i 0524 10:49:51.124027 52 compiler.py:653] handle pyjt_include/home/karthik/.local/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from WindowUI import WindowUI
  File "/home/karthik/Documents/deeplearning/DeepFaceDrawing-Jittor/WindowUI.py", line 18, in <module>
    jt.flags.use_cuda = 1
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.flags)).

Types of your inputs are:
 self	= flags,
 arg	= int,

The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)

Failed reason:[f 0524 10:49:51.790183 52 cuda_flags.cc:30] Check failed: value==0  No CUDA found.
karthik@karthik:~/Do

**Comment by Jittor** [comment]
no cuda found，you can comment out the use_cuda code “jt.flags.use_cuda=1”



---Original---
From: ***@***.***&gt;
Date: Mon, May 24, 2021 13:35 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Jittor/jittor] got runtime error ...any idea (#218)




 
on3.8 -I/home/karthik/.local/lib/python3.8/site-packages/pybind11/include
 [i 0524 10:49:50.172849 52 compiler.py:898] extension_suffix: .cpython-38-x86_64-linux-gnu.so
 [i 0524 10:49:50.427291 52 init.py:168] Total mem: 10.62GB, using 3 procs for compiling.
 [i 0524 10:49:50.993130 52 jit_compiler.cc:20] Load cc_path: /usr/bin/g++
 [i 0524 10:49:51.052464 52 init.py:249] Found mpicc(4.0.3) at /usr/bin/mpicc.
 [i 0524 10:49:51.124027 52 compiler.py:653] handle pyjt_include/home/karthik/.local/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
 Traceback (most recent call last):
 File "demo.py", line 4, in 
 from WindowUI import WindowUI
 File "/home/karthik/Documents/deeplearning/DeepFaceDrawing-Jittor/WindowUI.py", line 18, in 
 jt.flags.use_cuda = 1
 RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.flags)).
 
Types of your inputs are:
 self= flags,
 arg= int,
 
The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)
 
Failed reason:[f 0524 10:49:51.790183 52 cuda_flags.cc:30] Check failed: value==0  No CUDA found.
 ***@***.***:~/Do

**Comment by Trivenu** [comment]
hi...if i comment that ..i got this below error 
.8 -I/home/karthik/.local/lib/python3.8/site-packages/pybind11/include
[i 0524 11:22:15.258327 80 compiler.py:898] extension_suffix: .cpython-38-x86_64-linux-gnu.so
[i 0524 11:22:16.048166 80 __init__.py:168] Total mem: 10.62GB, using 3 procs for compiling.
[i 0524 11:22:17.163323 80 jit_compiler.cc:20] Load cc_path: /usr/bin/g++
[i 0524 11:22:17.271199 80 __init__.py:249] Found mpicc(4.0.3) at /usr/bin/mpicc.
[i 0524 11:22:17.443779 80 compiler.py:653] handle pyjt_include/home/karthik/.local/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
QObject::moveToThread: Current thread (0x1fabcc0) is not the object's thread (0x2c0f220).
Cannot move to target thread (0x1fabcc0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/karthik/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

Aborted (core dumped)

**Comment by Jittor** [comment]
it looks like a qt dependency error，not jittor，you can search this error about qt，you may find some clues



---Original---
From: ***@***.***&gt;
Date: Mon, May 24, 2021 13:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Jittor/jittor] got runtime error ...any idea (#218)




 
hi...if i comment that ..i got this below error
 .8 -I/home/karthik/.local/lib/python3.8/site-packages/pybind11/include
 [i 0524 11:22:15.258327 80 compiler.py:898] extension_suffix: .cpython-38-x86_64-linux-gnu.so
 [i 0524 11:22:16.048166 80 init.py:168] Total mem: 10.62GB, using 3 procs for compiling.
 [i 0524 11:22:17.163323 80 jit_compiler.cc:20] Load cc_path: /usr/bin/g++
 [i 0524 11:22:17.271199 80 init.py:249] Found mpicc(4.0.3) at /usr/bin/mpicc.
 [i 0524 11:22:17.443779 80 compiler.py:653] handle pyjt_include/home/karthik/.local/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
 QObject::moveToThread: Current thread (0x1fabcc0) is not the object's thread (0x2c0f220).
 Cannot move to target thread (0x1fabcc0)
 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/karthik/.local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
 This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 
Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.
 
Aborted (core dumped)

**Comment by Trivenu** [comment]
thanks!!!

**Comment by Study1coding** [comment]
没有注释jt.flags.use_cuda = 1的情况
Traceback (most recent call last):

  File "D:\semester\insemester_plan\4sophomore\学习资料\B样条神经网络生成曲面\可微渲染\基础教程jittor\jrender-main\demo1-render.py", line 3, in <module>
    jt.flags.use_cuda = 1

RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.Flags.use_cuda)).

Types of your inputs are:
 self	= Flags,
 arg	= int,

The function declarations are:
 void _set_use_cuda(int v)
 void _set_use_cuda(bool v)

Failed reason:[f 0420 22:49:35.239000 04 cuda_flags.cc:37] Check failed: value==0  No CUDA found.
-------------------------------------------------------------------------------------------------------------------------
注释了jt.flags.use_cuda = 1之后
File "D:\semester\insemester_plan\4sophomore\学习资料\B样条神经网络生成曲面\可微渲染\基础教程jittor\jrender-main\demo1-render.py", line 46, in main
    image = rgb.numpy()[0].transpose((1, 2, 0))

RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.numpy)).

Types of your inputs are:
 self	= Var,
 args	= (),

The function declarations are:
 ArrayArgs fetch_sync()

Failed reason:[f 0420 22:56:22.878000 04 op.cc:151] Check failed: flags.get(NodeFlags::_cpu)  Something wrong... Could you please report this issue?
 Op code doesn't have cpu version
