### ISSUE TITLE
doesn't support cuda 11

### ISSUE THREAD

**Issue by amiltonwong** [Jittor/jittor#228]
Hi, all,

It seems the current jittor doesn't support CUDA 11. Any hints to solve this issue?   (I can't downgrade to CUDA 10.x because my GPU is 30XX series)

```
>>> import jittor
[i 0618 03:58:48.692080 20 lock.py:58] Create lock file:/root/.cache/jittor/default/jittor.lock
[i 0618 03:58:48.768212 20 compiler.py:857] Jittor(1.2.3.32) src: /root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor
[i 0618 03:58:48.772921 20 compiler.py:858] g++ at /usr/bin/g++(5.4.0)
[i 0618 03:58:48.773126 20 compiler.py:859] cache_path: /root/.cache/jittor/default/g++
[i 0618 03:58:48.792206 20 compiler.py:809] Found nvcc(11.0.194) at /usr/local/cuda-11.0/bin/nvcc
[i 0618 03:58:49.355502 20 __init__.py:258] Found gdb(7.11.1) at /usr/bin/gdb.
[i 0618 03:58:49.412150 20 __init__.py:258] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 0618 03:58:49.450475 20 compiler.py:918] py_include: -I/root/anaconda3/envs/pytorch1.6/include/python3.7m -I/root/anaconda3/envs/pytorch1.6/include/python3.7m
[i 0618 03:58:49.468825 20 compiler.py:920] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 0618 03:58:49.469077 20 compiler.py:30] Create cache dir: /root/.cache/jittor/default/g++/jit
[i 0618 03:58:49.469254 20 compiler.py:30] Create cache dir: /root/.cache/jittor/default/g++/obj_files
[i 0618 03:58:49.469397 20 compiler.py:30] Create cache dir: /root/.cache/jittor/default/g++/gen
[i 0618 03:58:49.469537 20 compiler.py:30] Create cache dir: /root/.cache/jittor/default/g++/checkpoints

[i 0618 03:59:04.396660 64 compiler.py:1041] OS type:ubuntu OS key:ubuntu
[i 0618 03:59:05.397604 64 __init__.py:169] Total mem: 62.82GB, using 16 procs for compiling.
Compiling jittor_core(144/144) used: 34.341s eta: 0.000s
[i 0618 03:59:40.468344 64 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
[i 0618 03:59:40.468370 64 jit_compiler.cc:24] Load nvcc_path: /usr/local/cuda-11.0/bin/nvcc
[i 0618 03:59:40.468543 64 init.cc:55] Found cuda archs: [86,]
[i 0618 03:59:41.267295 64 compile_extern.py:422] mpicc not found, distribution disabled.
[i 0618 03:59:41.267736 64 compiler.py:30] Create cache dir: /root/.cache/jittor/cutt
[i 0618 03:59:41.267991 64 compile_extern.py:248] Downloading cutt...
Downloading https://codeload.github.com/Jittor/cutt/zip/v1.1 to /root/.cache/jittor/cutt/cutt-1.1.zip
303104it [00:01, 290713.60it/s]
[i 0618 03:59:42.341214 64 compile_extern.py:261] installing cutt...
mkdir -p build
g++ -fPIC -c -I /usr/local/cuda-11.0/include -std=c++11  -O3  -march=native -o build/cutt.o src/cutt.cpp
echo -e 'build/\c' > build/cutt.d
g++ -fPIC -M -I /usr/local/cuda-11.0/include -std=c++11  -O3  -march=native src/cutt.cpp >> build/cutt.d
g++ -fPIC -c -I /usr/local/cuda-11.0/include -std=c++11  -O3  -march=native -o build/cuttplan.o src/cuttplan.cpp
echo -e 'build/\c' > build/cuttplan.d
g++ -fPIC -M -I /usr/local/cuda-11.0/include -std=c++11  -O3  -march=native src/cuttplan.cpp >> build/cuttplan.d
/usr/local/cuda-11.0/bin/nvcc -Xcompiler -fPIC -c -I /usr/local/cuda-11.0/include -std=c++11 -O3 -Xptxas -dlcm=ca -lineinfo -arch=compute_86  -code=sm_86  --cudart=shared -ccbin="/usr/bin/g++"  --resource-usage -Xcompiler ""  -D_FORCE_INLINES -o build/cuttkernel.o src/cuttkernel.cu
nvcc fatal   : Value 'compute_86' is not defined for option 'gpu-architecture'
Makefile:154: recipe for target 'build/cuttkernel.o' failed
make: *** [build/cuttkernel.o] Error 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor/__init__.py", line 25, in <module>
    from . import compile_extern
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor/compile_extern.py", line 474, in <module>
    setup_cutt()
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor/compile_extern.py", line 287, in setup_cutt
    install_cutt(cutt_path)
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor/compile_extern.py", line 266, in install_cutt
    run_cmd(f"make NVCC_GENCODE='{arch_flag} --cudart=shared -ccbin=\"{cc_path}\" ' nvcc_path='{nvcc_path}'", cwd=dirname)
  File "/root/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/jittor_utils/__init__.py", line 137, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: make NVCC_GENCODE=' -arch=compute_86  -code=sm_86  --cudart=shared -ccbin="/usr/bin/g++" ' nvcc_path='/usr/local/cuda-11.0/bin/nvcc'

```

Thanks~

**Comment by Jittor** [comment]
You need to install cuda 11.2+, cuda 11.0 is not supported 30XX gpu.
you can execute `python3.7 -m jittor_utils.install_cuda`, let jittor install cuda for you.
