### ISSUE TITLE
miniforge conda 环境下运行程序报 ‘’file libcublasLt.so not found‘’错误，本地python环境下运行没有这个错

### ISSUE THREAD

**Issue by xiashuo** [Jittor/jittor#232]
[i 0623 11:20:04.202472 72 compiler.py:857] Jittor(1.2.3.31) src: /home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor
[i 0623 11:20:04.208392 72 compiler.py:858] g++ at g++-7(7.4.0)
[i 0623 11:20:04.208555 72 compiler.py:859] cache_path: /home/kanq/.cache/jittor/default/g++-7
[i 0623 11:20:04.215134 72 __init__.py:258] Found /usr/local/cuda/bin/nvcc(10.0.117) at /usr/local/cuda/bin/nvcc.
[i 0623 11:20:04.221456 72 __init__.py:258] Found addr2line(2.31.1) at /usr/bin/addr2line.
[i 0623 11:20:04.241890 72 compiler.py:918] py_include: -I/home/kanq/miniforge3/envs/segment/include/python3.8 -I/home/kanq/miniforge3/envs/segment/include/python3.8
[i 0623 11:20:04.258780 72 compiler.py:920] extension_suffix: .cpython-38-aarch64-linux-gnu.so
[i 0623 11:20:04.574863 72 compiler.py:1041] OS type:uos OS key:ubuntu-aarch64
[i 0623 11:20:04.577378 72 __init__.py:169] Total mem: 15.59GB, using 5 procs for compiling.
[i 0623 11:20:04.788134 72 jit_compiler.cc:21] Load cc_path: g++-7
[i 0623 11:20:04.918754 72 init.cc:55] Found cuda archs: [75,]
[i 0623 11:20:04.934390 72 __init__.py:258] Found mpicc(3.1.3) at /usr/bin/mpicc.
[i 0623 11:20:04.980695 72 compiler.py:659] handle pyjt_include/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/extern/mpi/inc/mpi_warper.h
[i 0623 11:20:05.012767 72 compile_extern.py:325] Downloading nccl...
[i 0623 11:20:05.068467 72 compile_extern.py:19] found /usr/local/cuda/include/cublas.h
[i 0623 11:20:05.077046 72 compile_extern.py:19] found /usr/local/cuda/lib64/libcublas.so
[w 0623 11:20:05.078044 72 compile_extern.py:168] CUDA found but cublas is not loaded:
Traceback (most recent call last):
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/compile_extern.py", line 164, in setup_cuda_extern
    setup_cuda_lib(lib_name)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/compile_extern.py", line 200, in setup_cuda_lib
    cublas_lt_lib_path = search_file([cuda_lib, extra_lib_path, "/usr/lib/x86_64-linux-gnu", "/usr/lib"], f"libcublasLt.so", nvcc_version)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/compile_extern.py", line 21, in search_file
    LOG.f(f"file {name} not found in {dirs}")
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor_utils/__init__.py", line 64, in f
    def f(self, *msg): self._log('f', 0, *msg)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor_utils/__init__.py", line 49, in _log
    cc.log(fileline, level, verbose, msg)
RuntimeError: [f 0623 11:20:05.077436 72 compile_extern.py:21] file libcublasLt.so not found in ['/usr/local/cuda/lib64', '/usr/local/cuda/targets/x86_64-linux/lib', '/usr/lib/x86_64-linux-gnu', '/usr/lib']

在conda环境下，运行程序会报上面的错误，但是并不影响程序继续运行的结果。当我在本地纯python环境下运行时，就没有上面这个错误。

**Comment by Jittor** [comment]
感谢您的反馈，您试试最新版本1.2.3.40？
用如下命令更新：
```
python3.8 -m pip install jittor -U
```

**Comment by xiashuo** [comment]
Traceback (most recent call last):
&nbsp; File "train.py", line 1, in <module&gt;
&nbsp; &nbsp; import jittor as jt
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module&gt;
&nbsp; &nbsp; from . import compiler
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/compiler.py", line 1091, in <module&gt;
&nbsp; &nbsp; jit_utils.download(url, extra_obj)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor_utils/__init__.py", line 212, in download
&nbsp; &nbsp; urllib.request.urlretrieve(url, filename)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 247, in urlretrieve
&nbsp; &nbsp; with contextlib.closing(urlopen(url, data)) as fp:
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 222, in urlopen
&nbsp; &nbsp; return opener.open(url, data, timeout)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 531, in open
&nbsp; &nbsp; response = meth(req, response)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 640, in http_response
&nbsp; &nbsp; response = self.parent.error(
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 569, in error
&nbsp; &nbsp; return self._call_chain(*args)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 502, in _call_chain
&nbsp; &nbsp; result = func(*args)
&nbsp; File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 649, in http_error_default
&nbsp; &nbsp; raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found



升级1.2.3.40版本后，报了上面这个错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 中午11:31
收件人: ***@***.***&gt;; 
抄送: "(6X13N4) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jittor/jittor] miniforge conda 环境下运行程序报 ‘’file libcublasLt.so not found‘’错误，本地python环境下运行没有这个错 (#232)





 
感谢您的反馈，您试试最新版本1.2.3.40？
 用如下命令更新：
 python3.8 -m pip install jittor -U
