### ISSUE TITLE
arcch平台UOS系统，原始版本升级到jittor 1.2.3.40或者1.2.3.42版本后，运行程序报“urllib.error.HTTPError: HTTP Error 404: Not Found”

### ISSUE THREAD

**Issue by xiashuo** [Jittor/jittor#235]
Traceback (most recent call last):
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor/compiler.py", line 1091, in <module>
    jit_utils.download(url, extra_obj)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/site-packages/jittor_utils/__init__.py", line 212, in download
    urllib.request.urlretrieve(url, filename)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/kanq/miniforge3/envs/segment/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

arcch平台UOS系统，原始版本升级到jittor 1.2.3.40或者1.2.3.42版本后，就报了上面了错误，请问这可能是什么问题？1.2.3.32版本下没有这个问题。

**Comment by Jittor** [comment]
谢谢您的反馈，您试试更新最新版本1.2.3.44？
如果还是有问题，您可以提供一下完整的日志

**Comment by Jittor** [comment]
现在最新版本不需要提供环境变量`os_key`，最新版本会自行判断，您可以`unset os_key`删除该环境变量

**Comment by xiashuo** [comment]
升到最新版后，问题解决了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月25日(星期五) 中午11:31
收件人: ***@***.***&gt;; 
抄送: "(6X13N4) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jittor/jittor] arcch平台UOS系统，原始版本升级到jittor 1.2.3.40或者1.2.3.42版本后，运行程序报“urllib.error.HTTPError: HTTP Error 404: Not Found” (#235)





 
现在最新版本不需要提供环境变量os_key，最新版本会自行判断，您可以unset os_key删除该环境变量
