### ISSUE TITLE
1.2.3.44版本中nn.cross_entropy_loss函数，传入weight参数报错

### ISSUE THREAD

**Issue by xiashuo** [Jittor/jittor#236]
Traceback (most recent call last):
  File "/disk_sda/xs/projects/xuexian-jittor/train.py", line 124, in <module>
    main()
  File "/disk_sda/xs/projects/xuexian-jittor/train.py", line 119, in main
    train(model, train_loader, optimizer, epoch, learning_rate, writer, epochs)
  File "/disk_sda/xs/projects/xuexian-jittor/train.py", line 54, in train
    loss = nn.cross_entropy_loss(pred, target, weight=jt.array([1, 20, 8, 4]),ignore_index=255)  # fix a bug
  File "/home/kqgis/anaconda3/envs/xuexian-jittor/lib/python3.8/site-packages/jittor/nn.py", line 214, in cross_entropy_loss
    loss = (logsum - (output*target).sum(1)) * target_weight
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.__mul__)).

Types of your inputs are:
 self	= Var,
 b	= Var,

The function declarations are:
 VarHolder* multiply(VarHolder* x, VarHolder* y)

Failed reason:[f 0625 14:07:57.001614 44 binary_op.cc:522] Check failed xshape(8388608) == yshape(512) Shape not match, x:float32[8388608,]  y:int32[32,512,512,]

下面是我的调用代码，我是按照pytorch里的参数格式传入的（4个类别），请问是我参数格式有误还是？
loss = nn.cross_entropy_loss(pred, target, weight=jt.array([1, 20, 8, 4]))  # fix a bug

**Comment by Jittor** [comment]
请问您`pred`， `target`的形状是怎样的呢？

**Comment by xiashuo** [comment]
pred: (32,4,512,512)
target: (32,512,512)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月25日(星期五) 下午2:27
收件人: ***@***.***&gt;; 
抄送: "(6X13N4) ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jittor/jittor] 1.2.3.44版本中nn.cross_entropy_loss函数，传入weight参数报错 (#236)





 
请问您pred， target的形状是怎样的呢？

**Comment by xiashuo** [comment]
> 请问您`pred`， `target`的形状是怎样的呢？

pred: (32,4,512,512)
target: (32,512,512)

**Comment by Jittor** [comment]
您好，感谢您的反馈，我们刚刚根据您反馈的形状编写了一个test，并没能复现出您的错误，这是我们写的test：https://github.com/Jittor/jittor/commit/aaf97d5f58a3fed8aa2f93be132a9ed9be8dd4a5

请您确认一下是否更新到了最新版本，因为以前旧版本是会有这个错误的。
如果还是有问题，您可以提供一下完整的日志给我们。再次感谢

**Comment by xiashuo** [comment]
> 您好，感谢您的反馈，我们刚刚根据您反馈的形状编写了一个test，并没能复现出您的错误，这是我们写的test：[aaf97d5](https://github.com/Jittor/jittor/commit/aaf97d5f58a3fed8aa2f93be132a9ed9be8dd4a5)
> 
> 请您确认一下是否更新到了最新版本，因为以前旧版本是会有这个错误的。
> 如果还是有问题，您可以提供一下完整的日志给我们。再次感谢

升级到1.2.3.45版，问题解决了，谢谢！这版本更新太快了，一天升级了3个版本哈哈

**Comment by Jittor** [comment]
为了快速支持大家，我们会光速更新的😆
