### ISSUE TITLE
运行jittor.test.test_example报错

### ISSUE THREAD

**Issue by Mountchicken** [Jittor/jittor#255]
你好，请问一下我在运行python -m jittor.test.test_example的时候出现了这样的问题，似乎和nvcc有关

> 
(jittor_gpu) wjp@wjp-System-Product-Name:~$ python -m jittor.test.test_example
[i 0805 17:20:53.835541 52 compiler.py:869] Jittor(1.2.3.87) src: /home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor
[i 0805 17:20:53.837007 52 compiler.py:870] g++ at /usr/local/bin/g++(5.4.0)
[i 0805 17:20:53.837062 52 compiler.py:871] cache_path: /home/wjp/.cache/jittor/default/g++
/bin/sh: 1: /usr/loca/cuda/bin/nvcc: not found
Traceback (most recent call last):
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor/compiler.py", line 892, in <module>
    nvcc_path = env_or_try_find('nvcc_path', 'nvcc') or \
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor/compiler.py", line 816, in env_or_try_find
    version = jit_utils.get_version(path)
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor_utils/__init__.py", line 260, in get_version
    version = run_cmd(output+" --version")
  File "/home/wjp/miniconda2/envs/jittor_gpu/lib/python3.7/site-packages/jittor_utils/__init__.py", line 143, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: /usr/loca/cuda/bin/nvcc --version

(jittor_gpu) wjp@wjp-System-Product-Name:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

**Comment by Jittor** [comment]
您的nvcc在什么位置呢，which nvcc输出怎样

**Comment by Jittor** [comment]
建议您让jittor帮您找到合适版本的nvcc和cuda，您可以运行python3 -m jittor_utils.install_cuda

**Comment by Mountchicken** [comment]
nvcc在 /usr/loacl/cuda-10.1/bin中，我也执行了 export nvcc_path="/usr/loacl/cuda-10.1/bin"的指令

**Comment by Mountchicken** [comment]
pytorch是能正常运行的

**Comment by Mountchicken** [comment]
然后我也测试jittor的其它代码，是可以正常运行的，包括在cpu上训练网络。但是只要指定jt.flags.use_cuda=1就会报错

**Comment by Jittor** [comment]
错误信息里面显示`Exception: Run cmd failed: /usr/loca/cuda/bin/nvcc --version`， 您的环境变量是不是`local`误写成`loca`了？
