### ISSUE TITLE
python -m jittor.test.test_example@ubuntu16+python3.8

### ISSUE THREAD

**Issue by HyperGroups** [Jittor/jittor#281]
hyper@intel:/usr/local/cuda$ python -m jittor.test.test.example
[i 1106 03:34:54.091816 28 compiler.py:944] Jittor(1.3.1.18) src: /home/hyper/.local/lib/python3.8/site-packages/jittor
[i 1106 03:34:54.093861 28 compiler.py:945] g++ at /usr/bin/g++(5.4.0)
[i 1106 03:34:54.093924 28 compiler.py:946] cache_path: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default
[i 1106 03:34:54.101029 28 __init__.py:372] Found nvcc(10.1.105) at /usr/bin/nvcc.
[i 1106 03:34:54.144537 28 __init__.py:372] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1106 03:34:54.148659 28 __init__.py:372] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1106 03:34:54.268504 28 compiler.py:997] cuda key:cu10.1.105_sm_61
[i 1106 03:34:54.304868 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61
[i 1106 03:34:54.304965 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/jit
[i 1106 03:34:54.305024 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/obj_files
[i 1106 03:34:54.305081 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/gen
[i 1106 03:34:54.305132 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/tmp
[i 1106 03:34:54.305188 28 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/checkpoints
[e 1106 03:34:58.600524 28 compiler.py:875] jit_utils updated, please rerun your command.
hyper@intel:/usr/local/cuda$ python -m jittor.test.test.example
[i 1106 03:35:03.800145 32 compiler.py:944] Jittor(1.3.1.18) src: /home/hyper/.local/lib/python3.8/site-packages/jittor
[i 1106 03:35:03.802495 32 compiler.py:945] g++ at /usr/bin/g++(5.4.0)
[i 1106 03:35:03.802558 32 compiler.py:946] cache_path: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default
[i 1106 03:35:03.805144 32 __init__.py:372] Found nvcc(10.1.105) at /usr/bin/nvcc.
[i 1106 03:35:03.853370 32 __init__.py:372] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1106 03:35:03.855939 32 __init__.py:372] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1106 03:35:03.977698 32 compiler.py:997] cuda key:cu10.1.105_sm_61
[i 1106 03:35:09.511158 32 __init__.py:187] Total mem: 15.61GB, using 5 procs for compiling.
nvcc fatal   : Path to libdevice library not specified6ss
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/__init__.py", line 157, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 1106 03:36:01.583748 32 log.cc:569] Check failed ret(256) == 0(0) Run cmd failed: "/usr/bin/nvcc"  "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/src" -I/opt/anaconda3/include/python3.8 -I/opt/anaconda3/include/python3.8 -DHAS_CUDA -I"/usr/local/cuda-10.1/include" -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/extern/cuda/inc"   -I"/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61"   -O2   -c -o "/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/extern/cuda/inc" 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 1303, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 147, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/__init__.py", line 211, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
RuntimeError: [f 1106 03:36:01.583748 32 log.cc:569] Check failed ret(256) == 0(0) Run cmd failed: "/usr/bin/nvcc"  "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/src" -I/opt/anaconda3/include/python3.8 -I/opt/anaconda3/include/python3.8 -DHAS_CUDA -I"/usr/local/cuda-10.1/include" -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/extern/cuda/inc"   -I"/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61"   -O2   -c -o "/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x28/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/extern/cuda/inc"

**Comment by WuTianyi321** [comment]
试试配置下nvcc.profile这个文件，这个文件里TOP就是cuda的路径，但默认路径是`/user/local/bin/`，直接指定cuda路径比如`TOP=/user/local/cuda`试试？
