### ISSUE TITLE
Problem@Ubuntu 16.04@python-enviroment

### ISSUE THREAD

**Issue by HyperGroups** [Jittor/jittor#282]
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jittor
[i 1106 21:05:50.208856 52 compiler.py:944] Jittor(1.3.1.18) src: /home/hyper/.local/lib/python3.8/site-packages/jittor
[i 1106 21:05:50.210880 52 compiler.py:945] g++ at /usr/bin/g++(5.4.0)
[i 1106 21:05:50.210967 52 compiler.py:946] cache_path: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default
[i 1106 21:05:50.213103 52 __init__.py:372] Found nvcc(10.1.105) at /usr/bin/nvcc.
[i 1106 21:05:50.254729 52 __init__.py:372] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1106 21:05:50.256745 52 __init__.py:372] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1106 21:05:50.343250 52 compiler.py:997] cuda key:cu10.1.105_sm_61
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 1032, in <module>
    py_include = jit_utils.get_py3_include_path()
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/__init__.py", line 445, in get_py3_include_path
    _py3_include_path = run_cmd(get_py3_config_path()+" --includes")
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/__init__.py", line 425, in get_py3_config_path
    raise RuntimeError(f"python3.{sys.version_info.minor}-config "
RuntimeError: python3.8-config not found in ['/usr/bin/python3.8-config', '/usr/bin/python38-config', '/usr/bin/python3.8-config', '/usr/local/bin/python3.8-config', '/opt/homebrew/bin/python3.8-config', '/usr/bin/python3-config'], please specify enviroment variable 'python_config_path', or install python3.8-dev

---
conda版本的python3.8.8

**Comment by HyperGroups** [comment]
>>> import jittor
[i 1106 21:22:04.516150 32 compiler.py:944] Jittor(1.3.1.18) src: /home/hyper/.local/lib/python3.8/site-packages/jittor
[i 1106 21:22:04.522991 32 compiler.py:945] g++ at /usr/bin/g++(5.4.0)
[i 1106 21:22:04.523568 32 compiler.py:946] cache_path: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default
[i 1106 21:22:04.530900 32 __init__.py:372] Found nvcc(10.1.105) at /usr/bin/nvcc.
[i 1106 21:22:04.582777 32 __init__.py:372] Found gdb(7.11.1) at /usr/bin/gdb.
[i 1106 21:22:04.584683 32 __init__.py:372] Found addr2line(2.26.1) at /usr/bin/addr2line.
[i 1106 21:22:04.695222 32 compiler.py:997] cuda key:cu10.1.105_sm_61
[i 1106 21:22:04.712557 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61
[i 1106 21:22:04.712694 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/jit
[i 1106 21:22:04.712764 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/obj_files
[i 1106 21:22:04.712828 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/gen
[i 1106 21:22:04.712889 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/tmp
[i 1106 21:22:04.712954 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/checkpoints
In file included from /home/hyper/.local/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:11:0,
                 from /home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
/home/hyper/.local/lib/python3.8/site-packages/jittor/src/pyjt/py_obj_holder.h:8:20: fatal error: Python.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 1162, in <module>
    check_cache_compile()
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 873, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 124, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/__init__.py", line 148, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/g++" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/src" -I/usr/include/python3.8 -I/usr/include/python3.8  -O2   -o "/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so"

**Comment by Jittor** [comment]
could you please try 'apt install python3.8-dev'



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 6, 2021 21:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Jittor/jittor] ***@***.*** ***@***.*** (Issue#282)




    
import jittor
 [i 1106 21:22:04.516150 32 compiler.py:944] Jittor(1.3.1.18) src: /home/hyper/.local/lib/python3.8/site-packages/jittor
 [i 1106 21:22:04.522991 32 compiler.py:945] g++ at /usr/bin/g++(5.4.0)
 [i 1106 21:22:04.523568 32 compiler.py:946] cache_path: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default
 [i 1106 21:22:04.530900 32 init.py:372] Found nvcc(10.1.105) at /usr/bin/nvcc.
 [i 1106 21:22:04.582777 32 init.py:372] Found gdb(7.11.1) at /usr/bin/gdb.
 [i 1106 21:22:04.584683 32 init.py:372] Found addr2line(2.26.1) at /usr/bin/addr2line.
 [i 1106 21:22:04.695222 32 compiler.py:997] cuda key:cu10.1.105_sm_61
 [i 1106 21:22:04.712557 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61
 [i 1106 21:22:04.712694 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/jit
 [i 1106 21:22:04.712764 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/obj_files
 [i 1106 21:22:04.712828 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/gen
 [i 1106 21:22:04.712889 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/tmp
 [i 1106 21:22:04.712954 32 compiler.py:34] Create cache dir: /home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/cu10.1.105_sm_61/checkpoints
 In file included from /home/hyper/.local/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:11:0,
 from /home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
 /home/hyper/.local/lib/python3.8/site-packages/jittor/src/pyjt/py_obj_holder.h:8:20: fatal error: Python.h: No such file or directory
 compilation terminated.
 Traceback (most recent call last):
 File "", line 1, in 
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor/init.py", line 18, in 
 from . import compiler
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 1162, in 
 check_cache_compile()
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 873, in check_cache_compile
 recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 124, in compile
 return do_compile(fix_cl_flags(cmd))
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
 run_cmd(cmd)
 File "/home/hyper/.local/lib/python3.8/site-packages/jittor_utils/init.py", line 148, in run_cmd
 raise Exception(err_msg)
 Exception: Run cmd failed: "/usr/bin/g++" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/home/hyper/.local/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/home/hyper/.local/lib/python3.8/site-packages/jittor/src" -I/usr/include/python3.8 -I/usr/include/python3.8  -O2   -o "/home/hyper/.cache/jittor/jt1.3.1/g++5.4.0/py3.8.8/Linux-4.15.0-1x88/IntelRCoreTMi3xc8/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so"
    
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
