### ISSUE TITLE
ubuntu18.04+python3.7.5 运行python3.7 -m jittor.test.test_example

### ISSUE THREAD

**Issue by lexa11s** [Jittor/jittor#283]
ubuntu18.04+python3.7.5 运行python3.7 -m jittor.test.test_example

## 完整报错
(25D) psdz@psdz:~/PycharmProjects/pythonProject1$ python3.7 -m jittor.test.test_example
[i 1108 15:59:34.095280 68 compiler.py:944] Jittor(1.3.1.18) src: /home/psdz/HSH/25D/lib/python3.7/site-packages/jittor
[i 1108 15:59:34.096658 68 compiler.py:945] g++ at /usr/bin/g++(7.5.0)
[i 1108 15:59:34.096701 68 compiler.py:946] cache_path: /home/psdz/.cache/jittor/jt1.3.1/g++7.5.0/py3.7.5/Linux-5.4.0-89x75/IntelRCoreTMi9xa7/default
[i 1108 15:59:34.098359 68 __init__.py:372] Found nvcc(10.0.130) at /usr/bin/nvcc.
[i 1108 15:59:34.133053 68 __init__.py:372] Found gdb(8.1.1) at /usr/bin/gdb.
[i 1108 15:59:34.134757 68 __init__.py:372] Found addr2line(2.30) at /usr/bin/addr2line.
[i 1108 15:59:34.196118 68 compiler.py:997] cuda key:cu10.0.130_sm_75
[i 1108 15:59:34.282972 68 __init__.py:187] Total mem: 62.74GB, using 16 procs for compiling.
Compiling jittor_core(146/146) used: 15.239s eta: 0.000s
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/psdz/HSH/25D/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/psdz/HSH/25D/lib/python3.7/site-packages/jittor/compiler.py", line 1310, in <module>
    import jittor_core as core
ImportError: /home/psdz/.cache/jittor/jt1.3.1/g++7.5.0/py3.7.5/Linux-5.4.0-89x75/IntelRCoreTMi9xa7/default/cu10.0.130_sm_75/jittor_core.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration

**Comment by lexa11s** [comment]
卸载CUDA Toolkit 后解决
