### ISSUE TITLE
win10 出现“NameError: name 'LOG' is not defined”

### ISSUE THREAD

**Issue by moshicaixi** [Jittor/jittor#286]
## Describe the bug
执行命令 “python -m jittor_utils.install_cuda”，报错“NameError: name 'LOG' is not defined”

## Full Log

(Jittor) PS D:\Desktop\segmentation transformer\PCT> python -m jittor_utils.install_cuda
Traceback (most recent call last):
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\lock.py", line 2, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\lock.py", line 6, in <module>
    import win32file
ImportError: DLL load failed while importing win32file: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Softwares\anaconda3\envs\Jittor\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Softwares\anaconda3\envs\Jittor\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\__init__.py", line 513, in <module>
    from jittor_utils import install_msvc
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\install_msvc.py", line 3, in <module>
    from jittor_utils.misc import download_url_to_local
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\misc.py", line 14, in <module>
    from jittor_utils import lock, LOG
  File "C:\Softwares\anaconda3\envs\Jittor\lib\site-packages\jittor_utils\lock.py", line 10, in <module>
    LOG.f("""pywin32 package not found, please install it.
NameError: name 'LOG' is not defined

环境：win10、cuda10.2、python3.8

**Comment by Jittor** [comment]
您好，您需要安装pywin32包

**Comment by moshicaixi** [comment]
> 您好，您需要安装pywin32包

OK,，我试试，非常感谢。后来我用linux系统，就没问题了。
