### ISSUE TITLE
当我运行 python3.9 -m jittor.test.test_resnet时出现了以下错误

### ISSUE THREAD

**Issue by BryantGao** [Jittor/jittor#329]
======================================================================
ERROR: test_resnet (__main__.TestResnetFp32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gz/anaconda3/lib/python3.9/site-packages/jittor/__init__.py", line 124, in inner
    ret = func(*args, **kw)
  File "/home/gz/anaconda3/lib/python3.9/site-packages/jittor/test/test_resnet.py", line 71, in test_resnet
    for data, target in self.train_loader:
  File "/home/gz/anaconda3/lib/python3.9/site-packages/jittor/dataset/dataset.py", line 506, in __iter__
    self._init_workers(index_list)
  File "/home/gz/anaconda3/lib/python3.9/site-packages/jittor/dataset/dataset.py", line 368, in _init_workers
    jt.migrate_all_to_cpu()
RuntimeError: [f 0523 22:27:37.631259 52 executor.cc:668]
Execute fused operator(0/531) failed.
[JIT Source]: /home/gz/.cache/jittor/jt1.3.4/g++9.4.0/py3.9.12/Linux-5.10.16.x28/IntelRCoreTMi9xa7/default/cu11.6.124/jit/__opkey0_broadcast_to__Tx_float32__DIM_7__BCAST_19__opkey1_reindex__Tx_float32__XDIM_4__YD___hash_5b8d431e1b0440f3_op.cc
[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[Input]: float32[64,3,7,7,], float32[100,3,224,224,],
[Output]: float32[100,64,112,112,],
[Async Backtrace]: ---
     /home/gz/anaconda3/lib/python3.9/runpy.py:197 <_run_module_as_main>
     /home/gz/anaconda3/lib/python3.9/runpy.py:87 <_run_code>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/test/test_resnet.py:151 <<module>>
     /home/gz/anaconda3/lib/python3.9/unittest/main.py:101 <__init__>
     /home/gz/anaconda3/lib/python3.9/unittest/main.py:271 <runTests>
     /home/gz/anaconda3/lib/python3.9/unittest/runner.py:184 <run>
     /home/gz/anaconda3/lib/python3.9/unittest/suite.py:84 <__call__>
     /home/gz/anaconda3/lib/python3.9/unittest/suite.py:122 <run>
     /home/gz/anaconda3/lib/python3.9/unittest/suite.py:84 <__call__>
     /home/gz/anaconda3/lib/python3.9/unittest/suite.py:122 <run>
     /home/gz/anaconda3/lib/python3.9/unittest/case.py:651 <__call__>
     /home/gz/anaconda3/lib/python3.9/unittest/case.py:592 <run>
     /home/gz/anaconda3/lib/python3.9/unittest/case.py:550 <_callTestMethod>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/__init__.py:124 <inner>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/test/test_resnet.py:81 <test_resnet>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/__init__.py:864 <__call__>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/test/test_resnet.py:34 <execute>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/__init__.py:864 <__call__>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/models/resnet.py:152 <execute>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/models/resnet.py:138 <_forward_impl>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/__init__.py:864 <__call__>
     /home/gz/anaconda3/lib/python3.9/site-packages/jittor/nn.py:846 <execute>
[Reason]: [f 0523 22:27:37.630926 52 helper_cuda.h:128] CUDA error at /home/gz/anaconda3/lib/python3.9/site-packages/jittor/src/mem/allocator/cuda_managed_allocator.cc:23  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)

----------------------------------------------------------------------
Ran 2 tests in 3.156s

FAILED (errors=2)

**Comment by BryantGao** [comment]
你好！感谢你这么及时的回复！
我的显卡是3090，显存是够的，
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 512.77       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| 33%   33C    P8    13W / 350W |    756MiB / 24576MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
我在wsl2上安装了这个框架
 This path may cause jittor found the wrong libs, please unset LD_LIBRARY_PATH and remove cuda lib path in Path.这个问题可能会是原因吗

**Comment by li-xl** [comment]
您试试设置环境变量use_cuda_managed_allocator=0，然后重新运行试试

**Comment by BryantGao** [comment]
好的！感谢！

**Comment by BryantGao** [comment]
> use_cuda_managed_allocator=0

还是不行，还是同样的问题

**Comment by li-xl** [comment]
是











祝好

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月23日(周一) 晚上11:49
收件人: ***@***.***&gt;;
抄送: "Xiang-Li ***@***.******@***.***&gt;;
主题: Re: [Jittor/jittor] 当我运行 python3.9 -m jittor.test.test_resnet时出现了以下错误 (Issue #329)




  
use_cuda_managed_allocator=0
  
还是不行，还是同样的问题

**Comment by li-xl** [comment]
是export&nbsp; use_cuda_managed_allocator=0
python ....
或者use_cuda_managed_allocator=0&nbsp; python&nbsp; ....这样吗











祝好

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月23日(周一) 晚上11:49
收件人: ***@***.***&gt;;
抄送: "Xiang-Li ***@***.******@***.***&gt;;
主题: Re: [Jittor/jittor] 当我运行 python3.9 -m jittor.test.test_resnet时出现了以下错误 (Issue #329)




  
use_cuda_managed_allocator=0
  
还是不行，还是同样的问题

**Comment by li-xl** [comment]
是export  use_cuda_managed_allocator=0
python ....
或者use_cuda_managed_allocator=0 python  ....这样吗
