### ISSUE TITLE
python3.7 -m jittor.test.test_example error

### ISSUE THREAD

**Issue by OrangeSodahub** [Jittor/jittor#358]
When I run `python3.7 -m jittor.test.test_example` occurred this:
```
(openmmlab_env) zonlin@YXYT3650:~/Openmmlab$ python -m jittor.test.test_cudnn_op
[i 0723 02:41:41.716334 84 compiler.py:955] Jittor(1.3.4.16) src: /home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor
[i 0723 02:41:41.719362 84 compiler.py:956] g++ at /usr/bin/g++(9.4.0)
[i 0723 02:41:41.719436 84 compiler.py:957] cache_path: /home/zonlin/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.10/Linux-5.14.0-1xcd/11thGenIntelRCx72/default
[i 0723 02:41:41.722585 84 __init__.py:411] Found nvcc(11.3.58) at /usr/bin/nvcc.
[i 0723 02:41:41.796267 84 __init__.py:411] Found gdb(20.04.1) at /usr/bin/gdb.
[i 0723 02:41:41.799297 84 __init__.py:411] Found addr2line(2.34) at /usr/bin/addr2line.
[i 0723 02:41:41.941888 84 compiler.py:1010] cuda key:cu11.3.58_sm_86
[i 0723 02:41:42.138377 84 __init__.py:227] Total mem: 15.36GB, using 5 procs for compiling.
sh: 1: cicc: not found
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor_utils/__init__.py", line 197, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0723 02:41:42.266495 84 log.cc:605] Check failed: ret>=0 && ret<=256  Run cmd failed: "/usr/bin/nvcc"  "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/src" -I/usr/include/python3.8 -I/usr/include/python3.8 -DHAS_CUDA -DIS_CUDA -I"/usr/include" -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/extern/cuda/inc"   -I"/home/zonlin/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.10/Linux-5.14.0-1xcd/11thGenIntelRCx72/default/cu11.3.58_sm_86"   -O2   -c -o "/home/zonlin/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.10/Linux-5.14.0-1xcd/11thGenIntelRCx72/default/cu11.3.58_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/extern/cuda/inc"  
return 32512. This might be an overcommit issue or out of memory. Try : sudo sysctl vm.overcommit_memory=1, or set enviroment variable `export DISABLE_MULTIPROCESSING=1`
"""

The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/compiler.py", line 1334, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/compiler.py", line 151, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor_utils/__init__.py", line 251, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
RuntimeError: [f 0723 02:41:42.266495 84 log.cc:605] Check failed: ret>=0 && ret<=256  Run cmd failed: "/usr/bin/nvcc"  "/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/src" -I/usr/include/python3.8 -I/usr/include/python3.8 -DHAS_CUDA -DIS_CUDA -I"/usr/include" -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/extern/cuda/inc"   -I"/home/zonlin/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.10/Linux-5.14.0-1xcd/11thGenIntelRCx72/default/cu11.3.58_sm_86"   -O2   -c -o "/home/zonlin/.cache/jittor/jt1.3.4/g++9.4.0/py3.8.10/Linux-5.14.0-1xcd/11thGenIntelRCx72/default/cu11.3.58_sm_86/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/home/zonlin/Openmmlab/openmmlab_env/lib/python3.8/site-packages/jittor/extern/cuda/inc"  
return 32512. This might be an overcommit issue or out of memory. Try : sudo sysctl vm.overcommit_memory=1, or set enviroment variable `export DISABLE_MULTIPROCESSING=1`
```
How could I solved it? plz

**Comment by OrangeSodahub** [comment]
I've solved it, just downgrade the CUDA and Pytorch.
Before: pytorch1.11+cu113
After: pytorch1.9+cu111
