### ISSUE TITLE
Errors in running 'python -m jittor_utils.install_cuda'

### ISSUE THREAD

**Issue by KyleLee1999** [Jittor/jittor#363]
(base) D:\Anaconda3\Scripts>python -m jittor.test.test_example
[i 0731 20:37:39.795811 92 compiler.py:955] Jittor(1.3.4.20) src: d:\anaconda3\lib\site-packages\jittor
[i 0731 20:37:39.810825 92 compiler.py:956] cl at C:\Users\Kyle Lee\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0731 20:37:39.810825 92 compiler.py:957] cache_path: C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default
[i 0731 20:37:39.813827 92 install_cuda.py:53] cuda_driver_version: [11, 5, 0]
[i 0731 20:37:39.825838 92 __init__.py:411] Found C:\Users\Kyle Lee\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\Kyle Lee\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0731 20:37:39.851862 92 compiler.py:1010] cuda key:cu11.2.67
[i 0731 20:37:39.852862 92 __init__.py:227] Total mem: 15.95GB, using 5 procs for compiling.
LINK : fatal error LNK1104: cannot open file 'Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default/jit_utils_core.cp39-win_amd64.pyd.def'
Traceback (most recent call last):
  File "D:\Anaconda3\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\Anaconda3\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "D:\Anaconda3\lib\site-packages\jittor\compiler.py", line 1180, in <module>
    check_cache_compile()
  File "D:\Anaconda3\lib\site-packages\jittor\compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "D:\Anaconda3\lib\site-packages\jittor\compiler.py", line 158, in compile
    return do_compile(fix_cl_flags(cmd))
  File "D:\Anaconda3\lib\site-packages\jittor\compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "D:\Anaconda3\lib\site-packages\jittor_utils\__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "C:\Users\Kyle Lee\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default\cu11.2.67\obj_files\cache_compile.cc.obj" "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default\cu11.2.67\obj_files\log.cc.obj" "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default\cu11.2.67\obj_files\tracer.cc.obj" "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default\cu11.2.67\obj_files\jit_utils.cc.obj" "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default\cu11.2.67\obj_files\str_utils.cc.obj" -Fe: "C:\Users\Kyle Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default/jit_utils_core.cp39-win_amd64.pyd"   -std:c++17      -LD   -EHa -MD -utf-8  -nologo -I"C:\Users\Kyle Lee\.cache\jittor\msvc\VC\include" -I"C:\Users\Kyle Lee\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\Kyle Lee\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\Kyle Lee\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"d:\anaconda3\lib\site-packages\jittor\src" -I"d:\anaconda3\include"  -O2    Lee\.cache\jittor\jt1.3.4\cl\py3.9.12\Windows-10-10.xdc\AMDRyzen73700Xx25\default/jit_utils_core.cp39-win_amd64.pyd".def" -IGNORE:4102 -IGNORE:4197 -IGNORE:4217  -link -LIBPATH:"d:\anaconda3\libs" python39.lib -LIBPATH:"C:\Users\Kyle Lee\.cache\jittor\msvc\VC\lib" -LIBPATH:"C:\Users\Kyle Lee\.cache\jittor\msvc\win10_kits\lib\um\x64" -LIBPATH:"C:\Users\Kyle Lee\.cache\jittor\msvc\win10_kits\lib\ucrt\x64" -DEF:""C:\Users\Kyle

**Comment by Jittor** [comment]
Thanks for reporting, this bug is fixed in latest version `1.3.5.6`, using `python3.x -m pip install jittor -U` to update jittor.

**Comment by wojciechteclaw** [comment]
Hi,
I got a question about the same bug in python. I'm working on:

- Windows 10
- Python 3.Virtualrtualenv)
- VS Code


I'm getting the same error as @KyleLee1999 
`Exception: Run cmd failed: "C:\Users\wojte\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe"`

Did you solve the issue, or could you give me some advice on what to change ??
