### ISSUE TITLE
jittor.linalg.einsum: index out of bounds exception if pattern contains space

### ISSUE THREAD

**Issue by alexfanqi** [Jittor/jittor#373]
## Minimal Reproduce
```
import jittor
a = jittor.ones((2,2))
b = jittor.ones((2,2))
jt.linalg.einsum('ac,     ac -> a', a, b) # <- one space is enough to cause the error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zpool-portable/shared/diffusion/diffusion-pytorch/lib/python3.10/site-packages/jittor/linalg.py", line 497, in einsum
    output_shape = [int(x) for x in einsum_outshape(string, args)]
  File "/zpool-portable/shared/diffusion/diffusion-pytorch/lib/python3.10/site-packages/jittor/linalg.py", line 495, in einsum_outshape
    return tuple(shps[(np_cpu.concatenate(inop[:-1])[:,None]==inop[-1]).argmax(0)].astype(np_cpu.int64))
IndexError: index 4 is out of bounds for axis 0 with size 4
```

## Expected behavior
The corresponding numpy einsum func has no such issue,
```
c = numpy.ones((2,2))
d = numpy.ones((2,2))
nump.einsum('a    c   , a c ->  a ', c , d) # <-whatever space has no effect
```
perhaps, need to strip any space in einsum_outshape or split by space?

**Comment by zhouwy19** [comment]
Thank you! We have fixed the error in this pr[https://github.com/Jittor/jittor/pull/378].

**Comment by alexfanqi** [comment]
Thanks, that solves the origin issue.

Another inconsistency with numpy is ellipsis.   
jittor:
```
>>> b = jt.ones((2))
>>> a = jt.ones((2,2))
>>> c = jt.linalg.einsum('...d,d->...d', a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/zpool-portable/shared/diffusion/modules/jittor/python/jittor/linalg.py", line 497, in einsum
    output_shape = [int(x) for x in einsum_outshape(string, args)]
  File "/zpool-portable/shared/diffusion/modules/jittor/python/jittor/linalg.py", line 495, in einsum_outshape
    return tuple(shps[(np_cpu.concatenate(inop[:-1])[:,None]==inop[-1]).argmax(0)].astype(np_cpu.int64))
IndexError: index 3 is out of bounds for axis 0 with size 3
```
numpy:
```
>>> a_n=np.ones((2,2))
>>> b_n=np.ones(2)
>>> c = np.einsum('...a,a->...a', a_n, b_n)
>>> c.shape
(2, 2)
```
Would it be possible to solve this one as well?

**Comment by Exusial** [comment]
Thank you! We have add epillsis support(numpy ver) in this pr (https://github.com/Jittor/jittor/pull/378).

**Comment by alexfanqi** [comment]
Many thanks! Now I can use einops with jittor.
