### ISSUE TITLE
Multi-GPU Training: Memory Issue

### ISSUE THREAD

**Issue by sylviayuan-sy** [Jittor/jittor#396]
## Describe the bug
I'm working on a jittor version of StyleGAN2. In training, the maximum batch size on a single GPU I can use is 16. However, when I try to use multiple GPUs, a memory error occurs with a batch size as small as 4 per GPU. 

## Full Log
100%|██████████| 1/1 [00:00<00:00, 11.82it/s][e 0926 09:44:26.555290 44 executor.cc:585]
=== display_memory_info ===
 total_cpu_ram: 62.78GB total_device_ram: 23.65GB
 hold_vars: 780 lived_vars: 19463 lived_ops: 31196
 update queue: 757/1225
 name: sfrl is_device: 1 used: 35.43GB(86.1%) unused: 5.707GB(13.9%) total: 41.14GB
 name: sfrl is_device: 1 used:  1.51MB(7.19%) unused: 19.49MB(92.8%) total:    21MB
 name: sfrl is_device: 0 used:  1.51MB(7.19%) unused: 19.49MB(92.8%) total:    21MB
 name: sfrl is_device: 0 used: 2.622MB(87.4%) unused:   387KB(12.6%) total:     3MB
 name: temp is_device: 0 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: temp is_device: 1 used: 5.907GB(95.9%) unused: 260.4MB(4.13%) total: 6.161GB
 cpu&gpu: 47.34GB gpu: 47.32GB cpu:    24MB
 free: cpu(300.6MB) gpu(    0 B)
===========================

[e 0926 09:44:26.558573 04 executor.cc:585]
=== display_memory_info ===
 total_cpu_ram: 62.78GB total_device_ram: 23.65GB
 hold_vars: 780 lived_vars: 19463 lived_ops: 31196
 update queue: 757/1225
 name: sfrl is_device: 1 used: 35.44GB(86%) unused: 5.746GB(14%) total: 41.18GB
 name: sfrl is_device: 1 used:  1.51MB(7.19%) unused: 19.49MB(92.8%) total:    21MB
 name: sfrl is_device: 0 used:  1.51MB(7.19%) unused: 19.49MB(92.8%) total:    21MB
 name: sfrl is_device: 0 used: 2.622MB(87.4%) unused:   387KB(12.6%) total:     3MB
 name: temp is_device: 0 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: temp is_device: 1 used: 5.907GB(95.9%) unused: 260.4MB(4.13%) total: 6.161GB
 cpu&gpu: 47.39GB gpu: 47.36GB cpu:    24MB
 free: cpu(300.4MB) gpu(    0 B)
===========================

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/train.py", line 96, in <module>
    train()
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/train.py", line 18, in train
    training_loop(cfg)
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/training/training_loop.py", line 217, in training_loop
    jt.sync_all()
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync_all)).

Types of your inputs are:
 self   = module,
 args   = (),

The function declarations are:
 void sync_all(bool device_sync=false)

Failed reason:[f 0926 09:44:26.560734 44 mem_info.cc:197]
*******************
GPU memory is overflow, please reduce your batch_size or data size!
Total: 23.65GB Used: 47.32GB

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/train.py", line 96, in <module>
    train()
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/train.py", line 18, in train
    training_loop(cfg)
  File "/home/yuanlu/StyleGAN2-Jittor/stylegan2-jittor-min/training/training_loop.py", line 217, in training_loop
    jt.sync_all()
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync_all)).

Types of your inputs are:
 self   = module,
 args   = (),

The function declarations are:
 void sync_all(bool device_sync=false)

Failed reason:[f 0926 09:44:26.560704 04 mem_info.cc:197]
*******************
GPU memory is overflow, please reduce your batch_size or data size!
Total: 23.65GB Used: 47.36GB
[e 0926 09:44:26.786383 44 helper_cuda.h:117] Peek CUDA error at /usr/local/lib/python3.7/dist-packages/jittor/src/mem/allocator/cuda_dual_allocator.h:101  code=700( cudaErrorIllegalAddress ) _cudaLaunchHostFunc(0, &to_free_allocation, 0)
[e 0926 09:44:26.790647 04 helper_cuda.h:117] Peek CUDA error at /usr/local/lib/python3.7/dist-packages/jittor/src/mem/allocator/cuda_dual_allocator.h:101  code=700( cudaErrorIllegalAddress ) _cudaLaunchHostFunc(0, &to_free_allocation, 0)
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0926 09:44:27.095601 44 helper_cuda.h:128] CUDA error at /usr/local/lib/python3.7/dist-packages/jittor/extern/cuda/nccl/src/nccl_wrapper.cc:57  code=1( unhandled cuda error ) ncclCommDestroy(comm)
  what():  [f 0926 09:44:27.095576 04 helper_cuda.h:128] CUDA error at /usr/local/lib/python3.7/dist-packages/jittor/extern/cuda/nccl/src/nccl_wrapper.cc:57  code=1( unhandled cuda error ) ncclCommDestroy(comm)
[jittor05:46731] *** Process received signal ***
[jittor05:46731] Signal: Aborted (6)
[jittor05:46731] Signal code:  (-6)
[jittor05:46732] *** Process received signal ***
[jittor05:46732] Signal: Aborted (6)
[jittor05:46732] Signal code:  (-6)
[jittor05:46731] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef10)[0x7f45dd13ff10]
[jittor05:46731] [ 1] [jittor05:46732] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef10)[0x7f24a3818f10]
[jittor05:46732] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f24a3818e87]
[jittor05:46732] [ 2] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f45dd13fe87]
[jittor05:46731] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f24a381a7f1]
[jittor05:46732] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f45dd1417f1]
[jittor05:46731] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9d0a9)[0x7f249fb4c0a9]
[jittor05:46732] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa8506)[0x7f249fb57506]
[jittor05:46732] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9d0a9)[0x7f45d94280a9]
[jittor05:46731] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa8506)[0x7f45d9433506]
[jittor05:46731] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa7529)[0x7f249fb56529]
[jittor05:46732] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa7529)[0x7f45d9432529]
[jittor05:46731] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x96)[0x7f45d9432c96]
[jittor05:46731] [ 7] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x96)[0x7f249fb56c96]
[jittor05:46732] [ 7] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10774)[0x7f45d9183774]
[jittor05:46731] [ 8] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10774)[0x7f249f8a7774]
[jittor05:46732] [ 8] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x126)[0x7f249f8a8136]
[jittor05:46732] [ 9] /home/yuanlu/.cache/jittor/jt1.3.2/g++7.5.0/py3.7.5/Linux-4.15.0-1xe7/IntelRXeonRCPUx00/default/cu10.2.89_sm_75/custom_ops/gen_ops_nccl_broadcast_nccl_reduce_nccl_all_reduce___hash61eab7.cpython-37m-x86_64-linux-gnu.so(_Z5checkI12ncclResult_tEvT_PKcS3_i/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_Resume+0x126)[0x7f45d9184136]
[jittor05:46731] [ 9] /home/yuanlu/.cache/jittor/jt1.3.2/g++7.5.0/py3.7.5/Linux-4.15.0-1xe7/IntelRXeonRCPUx00/default/cu10.2.89_sm_75/custom_ops/gen_ops_nccl_broadcast_nccl_reduce_nccl_all_reduce___hash61eab7.cpython-37m-x86_64-linux-gnu.so(_Z5checkI12ncclResult_tEvT_PKcS3_i+0x16a)[0x7f457395c8ba]
[jittor05:46731] [10] /home/yuanlu/.cache/jittor/jt1.3.2/g++7.5.0/py3.7.5/Linux-4.15.0-1xe7/IntelRXeonRCPUx00/default/cu10.2.89_sm_75/custom_ops/gen_ops_nccl_broadcast_nccl_reduce_nccl_all_reduce___hash61eab7.cpython-37m-x86_64-linux-gnu.so(_ZN6jittor11nccl_initerD2Ev+0x79)[0x7f457395c939]
[jittor05:46731] +0x16a)[0x7f243e1d58ba]
[jittor05:46732] [10] /home/yuanlu/.cache/jittor/jt1.3.2/g++7.5.0/py3.7.5/Linux-4.15.0-1xe7/IntelRXeonRCPUx00/default/cu10.2.89_sm_75/custom_ops/gen_ops_nccl_broadcast_nccl_reduce_nccl_all_reduce___hash61eab7.cpython-37m-x86_64-linux-gnu.so(_ZN6jittor11nccl_initerD2Ev+0x79)[0x7f243e1d5939]
[jittor05:46732] [11] [11] /lib/x86_64-linux-gnu
/libc.so.6(+0x43031)[0x7f45dd144031]
[jittor05:46731] /lib/x86_64-linux-gnu/libc.so.6(+0x43031)[0x7f24a381d031]
[jittor05:46732] [12] [12] /lib/x86_64-linux-gnu/libc.so.6(+0x4312a)[0x7f45dd14412a]
[jittor05:46731] [13] /lib/x86_64-linux-gnu/libc.so.6(+0x4312a)[0x7f24a381d12a]
[jittor05:46732] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xee)[0x7f24a37fbc8e/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xee)[0x7f45dd122c8e]
[jittor05:46731] [14] ]
[jittor05:46732] [14] python3.7(_start+0x2a)[0x5d141a]
[jittor05:46731] *** End of error message ***
python3.7(_start+0x2a)[0x5d141a]
[jittor05:46732] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node jittor05 exited on signal 6 (Aborted).
--------------------------------------------------------------------------

## Minimal Reproduce
I have attached a zip file containing to reproduce the error. To reproduce, run train.sh. 
[stylegan2-jittor-min.zip](https://github.com/Jittor/jittor/files/9642331/stylegan2-jittor-min.zip)

## Expected behavior
I would expect the code to execute without memory problem for a larger batch size.

**Comment by 0407nancy** [comment]
I have the similar problem, how do you solve the problem?
