### ISSUE TITLE
conda环境下运行python3.7 -m jittor.test.test_example报 AssertionError

### ISSUE THREAD

**Issue by Tsukihi-Araragi** [Jittor/jittor#398]
[##](url) Describe the bug
A clear and concise description of what the bug is. 使用中文也可以。

## Full Log
`[i 0929 09:43:48.598055 40 compiler.py:955] Jittor(1.3.5.16) src: /home/tdb/.local/lib/python3.7/site-packages/jittor
[i 0929 09:43:48.600386 40 compiler.py:956] g++ at /usr/bin/g++(11.2.0)
[i 0929 09:43:48.600491 40 compiler.py:957] cache_path: /home/tdb/.cache/jittor/jt1.3.5/g++11.2.0/py3.7.0/Linux-5.15.0-4xc8/IntelRXeonRCPUxf5/default
[i 0929 09:43:48.660630 40 __init__.py:411] Found gdb(12.0.90) at /usr/bin/gdb.
[i 0929 09:43:48.663218 40 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
Traceback (most recent call last):
  File "/home/tdb/anaconda3/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/tdb/anaconda3/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/tdb/.local/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/tdb/.local/lib/python3.7/site-packages/jittor/compiler.py", line 1180, in <module>
    check_cache_compile()
  File "/home/tdb/.local/lib/python3.7/site-packages/jittor/compiler.py", line 891, in check_cache_compile
    assert jit_utils.cc
AssertionError
`
Provide a full log of Jittor execution, Jittor will log environment information which help us to locate your bugs. Provide a screenshot is also acceptable.

## Minimal Reproduce

Reproduce this error with a file or several lines of code. 
If it is not possible, leave it blank.

## Expected behavior

If you are submitting an issue for the first time, please refer to [our guideline](https://github.com/Jittor/jittor/issues/238)

**Comment by Exusial** [comment]
您好，您这边清空cache看一下能否运行呢？

**Comment by WangSuhang123** [comment]
> 您好，您这边清空cache看一下能否运行呢？

依旧无法运行，报错信息：(jittor) wsh@wsh:~/DevelopCode/JDet/JDet-master$ python tools/run_net.py --config-file=configs/s2anet/s2anet_r50_fpn_1x_dota.py --task=train
[i 0924 22:29:46.938747 76 compiler.py:956] Jittor(1.3.10.0) src: /home/wsh/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor
[i 0924 22:29:46.941109 76 compiler.py:957] g++ at /usr/bin/g++(11.4.0)
[i 0924 22:29:46.941169 76 compiler.py:958] cache_path: /home/wsh/.cache/jittor/jt1.3.10/g++11.4.0/py3.8.13/Linux-6.8.0-83x28/12thGenIntelRCx5b/03f2/default
[i 0924 22:29:46.948717 76 __init__.py:412] Found nvcc(13.0.88) at /usr/local/cuda-13/bin/nvcc.
[i 0924 22:29:47.023248 76 __init__.py:412] Found gdb(22.04.2) at /usr/bin/gdb.
[i 0924 22:29:47.026804 76 __init__.py:412] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0924 22:29:48.878987 76 compiler.py:1013] cuda key:cu13.0.88_sm_86
Traceback (most recent call last):
  File "tools/run_net.py", line 2, in <module>
    import jittor as jt
  File "/home/wsh/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from .compiler import compiler
  File "/home/wsh/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 1207, in <module>
    check_cache_compile()
  File "/home/wsh/anaconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 892, in check_cache_compile
    assert jit_utils.cc
AssertionError
