### ISSUE TITLE
Segfault, exit

### ISSUE THREAD

**Issue by Unrealluver** [Jittor/jittor#42]
```
Train Epoch: 0 [0/766 (0%)]	Loss: 2.549237
Train Epoch: 0 [10/766 (1%)]	Loss: 2.571268
Train Epoch: 0 [20/766 (3%)]	Loss: 2.207814
Train Epoch: 0 [30/766 (4%)]	Loss: 2.274659
Train Epoch: 0 [40/766 (5%)]	Loss: 2.211828
Train Epoch: 0 [50/766 (7%)]	Loss: 2.293380
Train Epoch: 0 [60/766 (8%)]	Loss: 2.146942
Train Epoch: 0 [70/766 (9%)]	Loss: 2.183479
Train Epoch: 0 [80/766 (10%)]	Loss: 2.014589
Train Epoch: 0 [90/766 (12%)]	Loss: 2.112265
Train Epoch: 0 [100/766 (13%)]	Loss: 1.804279
Train Epoch: 0 [110/766 (14%)]	Loss: 2.146718
Train Epoch: 0 [120/766 (16%)]	Loss: 1.834919
Train Epoch: 0 [130/766 (17%)]	Loss: 1.726209
Train Epoch: 0 [140/766 (18%)]	Loss: 1.888488
Train Epoch: 0 [150/766 (20%)]	Loss: 1.838179
Train Epoch: 0 [160/766 (21%)]	Loss: 1.839886
Train Epoch: 0 [170/766 (22%)]	Loss: 1.664787
Train Epoch: 0 [180/766 (23%)]	Loss: 1.865397
Train Epoch: 0 [190/766 (25%)]	Loss: 1.781140
Train Epoch: 0 [200/766 (26%)]	Loss: 1.898801
Train Epoch: 0 [210/766 (27%)]	Loss: 2.073373
Train Epoch: 0 [220/766 (29%)]	Loss: 1.683119
Train Epoch: 0 [230/766 (30%)]	Loss: 1.850946
Train Epoch: 0 [240/766 (31%)]	Loss: 1.532344
Train Epoch: 0 [250/766 (33%)]	Loss: 1.873403
Train Epoch: 0 [260/766 (34%)]	Loss: 1.785834
Train Epoch: 0 [270/766 (35%)]	Loss: 2.242968
Train Epoch: 0 [280/766 (37%)]	Loss: 1.321845
Train Epoch: 0 [290/766 (38%)]	Loss: 1.664857
Train Epoch: 0 [300/766 (39%)]	Loss: 1.549777
Train Epoch: 0 [310/766 (40%)]	Loss: 1.533398
Train Epoch: 0 [320/766 (42%)]	Loss: 1.613966
Train Epoch: 0 [330/766 (43%)]	Loss: 1.576215
Train Epoch: 0 [340/766 (44%)]	Loss: 1.518085
Train Epoch: 0 [350/766 (46%)]	Loss: 1.476187
Train Epoch: 0 [360/766 (47%)]	Loss: 1.755865
Train Epoch: 0 [370/766 (48%)]	Loss: 1.718418
Train Epoch: 0 [380/766 (50%)]	Loss: 1.390453
Train Epoch: 0 [390/766 (51%)]	Loss: 1.609285
Train Epoch: 0 [400/766 (52%)]	Loss: 1.508573
Train Epoch: 0 [410/766 (54%)]	Loss: 1.486357
Train Epoch: 0 [420/766 (55%)]	Loss: 1.692045
Train Epoch: 0 [430/766 (56%)]	Loss: 1.495913
Train Epoch: 0 [440/766 (57%)]	Loss: 1.688043
Train Epoch: 0 [450/766 (59%)]	Loss: 1.500163
Train Epoch: 0 [460/766 (60%)]	Loss: 1.532048
Train Epoch: 0 [470/766 (61%)]	Loss: 1.780613
Train Epoch: 0 [480/766 (63%)]	Loss: 1.482994
Train Epoch: 0 [490/766 (64%)]	Loss: 1.345236
Train Epoch: 0 [500/766 (65%)]	Loss: 1.410739
Train Epoch: 0 [510/766 (67%)]	Loss: 1.459507
Train Epoch: 0 [520/766 (68%)]	Loss: 1.789894
Train Epoch: 0 [530/766 (69%)]	Loss: 1.479056
Train Epoch: 0 [540/766 (70%)]	Loss: 1.319969
Train Epoch: 0 [550/766 (72%)]	Loss: 1.776336
Train Epoch: 0 [560/766 (73%)]	Loss: 1.266944
Train Epoch: 0 [570/766 (74%)]	Loss: 1.530437
Train Epoch: 0 [580/766 (76%)]	Loss: 1.674438
Train Epoch: 0 [590/766 (77%)]	Loss: 1.614731
Train Epoch: 0 [600/766 (78%)]	Loss: 1.559749
Train Epoch: 0 [610/766 (80%)]	Loss: 1.461927
Train Epoch: 0 [620/766 (81%)]	Loss: 1.199259
Train Epoch: 0 [630/766 (82%)]	Loss: 1.775823
Train Epoch: 0 [640/766 (84%)]	Loss: 1.638302
Train Epoch: 0 [650/766 (85%)]	Loss: 1.037801
Train Epoch: 0 [660/766 (86%)]	Loss: 1.546026
Train Epoch: 0 [670/766 (87%)]	Loss: 1.183563
Train Epoch: 0 [680/766 (89%)]	Loss: 1.571771
Train Epoch: 0 [690/766 (90%)]	Loss: 1.238146
Train Epoch: 0 [700/766 (91%)]	Loss: 1.343132
Train Epoch: 0 [710/766 (93%)]	Loss: 1.268762
Train Epoch: 0 [720/766 (94%)]	Loss: 1.427858
Train Epoch: 0 [730/766 (95%)]	Loss: 1.425199
Train Epoch: 0 [740/766 (97%)]	Loss: 1.204324
Train Epoch: 0 [750/766 (98%)]	Loss: 1.215628
Train Epoch: 0 [760/766 (99%)]	Loss: 1.360539
Test Epoch: 0 [0/32 (0%)]	Acc: 0.062500
Test Epoch: 0 [1/32 (3%)]	Acc: 0.093750
Test Epoch: 0 [2/32 (6%)]	Acc: 0.156250
Test Epoch: 0 [3/32 (9%)]	Acc: 0.031250
Test Epoch: 0 [4/32 (12%)]	Acc: 0.187500
Test Epoch: 0 [5/32 (16%)]	Acc: 0.093750
Test Epoch: 0 [6/32 (19%)]	Acc: 0.125000
Test Epoch: 0 [7/32 (22%)]	Acc: 0.093750
Test Epoch: 0 [8/32 (25%)]	Acc: 0.062500
Test Epoch: 0 [9/32 (28%)]	Acc: 0.125000
Test Epoch: 0 [10/32 (31%)]	Acc: 0.093750
Test Epoch: 0 [11/32 (34%)]	Acc: 0.093750
Test Epoch: 0 [12/32 (38%)]	Acc: 0.093750
Test Epoch: 0 [13/32 (41%)]	Acc: 0.125000
Test Epoch: 0 [14/32 (44%)]	Acc: 0.156250
Test Epoch: 0 [15/32 (47%)]	Acc: 0.125000
Test Epoch: 0 [16/32 (50%)]	Acc: 0.000000
Test Epoch: 0 [17/32 (53%)]	Acc: 0.125000
Test Epoch: 0 [18/32 (56%)]	Acc: 0.156250
Test Epoch: 0 [19/32 (59%)]	Acc: 0.187500
Test Epoch: 0 [20/32 (62%)]	Acc: 0.062500
Test Epoch: 0 [21/32 (66%)]	Acc: 0.093750
Test Epoch: 0 [22/32 (69%)]	Acc: 0.062500
Test Epoch: 0 [23/32 (72%)]	Acc: 0.093750
Test Epoch: 0 [24/32 (75%)]	Acc: 0.218750
Test Epoch: 0 [25/32 (78%)]	Acc: 0.125000
Test Epoch: 0 [26/32 (81%)]	Acc: 0.156250
Test Epoch: 0 [27/32 (84%)]	Acc: 0.031250
Test Epoch: 0 [28/32 (88%)]	Acc: 0.187500
Test Epoch: 0 [29/32 (91%)]	Acc: 0.125000
Test Epoch: 0 [30/32 (94%)]	Acc: 0.156250
Test Epoch: 0 [31/32 (97%)]	Acc: 0.000000
Total test acc = 0.112
Train Epoch: 1 [0/766 (0%)]	Loss: 1.278104
Train Epoch: 1 [10/766 (1%)]	Loss: 1.445922
Train Epoch: 1 [20/766 (3%)]	Loss: 1.309801
Train Epoch: 1 [30/766 (4%)]	Loss: 1.511448
Train Epoch: 1 [40/766 (5%)]	Loss: 1.046027
Train Epoch: 1 [50/766 (7%)]	Loss: 1.019361
Train Epoch: 1 [60/766 (8%)]	Loss: 1.206879
Train Epoch: 1 [70/766 (9%)]	Loss: 1.339458
Train Epoch: 1 [80/766 (10%)]	Loss: 1.096838
Train Epoch: 1 [90/766 (12%)]	Loss: 1.282275
Train Epoch: 1 [100/766 (13%)]	Loss: 1.315636
Train Epoch: 1 [110/766 (14%)]	Loss: 1.093785
Train Epoch: 1 [120/766 (16%)]	Loss: 1.150581
Train Epoch: 1 [130/766 (17%)]	Loss: 1.378615
Train Epoch: 1 [140/766 (18%)]	Loss: 1.184623
Train Epoch: 1 [150/766 (20%)]	Loss: 1.092789
Train Epoch: 1 [160/766 (21%)]	Loss: 1.324679
Train Epoch: 1 [170/766 (22%)]	Loss: 1.350374
Train Epoch: 1 [180/766 (23%)]	Loss: 1.350134
Train Epoch: 1 [190/766 (25%)]	Loss: 1.318016
Train Epoch: 1 [200/766 (26%)]	Loss: 1.345922
Train Epoch: 1 [210/766 (27%)]	Loss: 1.395676
Train Epoch: 1 [220/766 (29%)]	Loss: 1.241677
Train Epoch: 1 [230/766 (30%)]	Loss: 1.053897
Train Epoch: 1 [240/766 (31%)]	Loss: 0.971859
Train Epoch: 1 [250/766 (33%)]	Loss: 1.124782
Train Epoch: 1 [260/766 (34%)]	Loss: 1.260339
Train Epoch: 1 [270/766 (35%)]	Loss: 1.219548
Train Epoch: 1 [280/766 (37%)]	Loss: 1.299369
Train Epoch: 1 [290/766 (38%)]	Loss: 1.213223
Train Epoch: 1 [300/766 (39%)]	Loss: 1.223816
Train Epoch: 1 [310/766 (40%)]	Loss: 1.175861
Train Epoch: 1 [320/766 (42%)]	Loss: 0.927709
Train Epoch: 1 [330/766 (43%)]	Loss: 1.400868
Train Epoch: 1 [340/766 (44%)]	Loss: 1.187871
Train Epoch: 1 [350/766 (46%)]	Loss: 1.214141
Train Epoch: 1 [360/766 (47%)]	Loss: 1.217095
Train Epoch: 1 [370/766 (48%)]	Loss: 0.985206
Train Epoch: 1 [380/766 (50%)]	Loss: 1.132003
Train Epoch: 1 [390/766 (51%)]	Loss: 1.066329
Train Epoch: 1 [400/766 (52%)]	Loss: 1.305349
Train Epoch: 1 [410/766 (54%)]	Loss: 1.225419
Train Epoch: 1 [420/766 (55%)]	Loss: 1.303159
Train Epoch: 1 [430/766 (56%)]	Loss: 0.998916
Train Epoch: 1 [440/766 (57%)]	Loss: 1.346875
Train Epoch: 1 [450/766 (59%)]	Loss: 1.254465
Train Epoch: 1 [460/766 (60%)]	Loss: 0.976315
Train Epoch: 1 [470/766 (61%)]	Loss: 1.451340
Train Epoch: 1 [480/766 (63%)]	Loss: 1.112767
Train Epoch: 1 [490/766 (64%)]	Loss: 1.305727
Train Epoch: 1 [500/766 (65%)]	Loss: 1.235950
Train Epoch: 1 [510/766 (67%)]	Loss: 1.148782
Train Epoch: 1 [520/766 (68%)]	Loss: 1.172709
Train Epoch: 1 [530/766 (69%)]	Loss: 1.142372
Train Epoch: 1 [540/766 (70%)]	Loss: 1.151231
Train Epoch: 1 [550/766 (72%)]	Loss: 0.951001
Train Epoch: 1 [560/766 (73%)]	Loss: 1.036463
Train Epoch: 1 [570/766 (74%)]	Loss: 1.361221
Train Epoch: 1 [580/766 (76%)]	Loss: 1.224620
Train Epoch: 1 [590/766 (77%)]	Loss: 1.237411
Train Epoch: 1 [600/766 (78%)]	Loss: 0.933225
Train Epoch: 1 [610/766 (80%)]	Loss: 0.970147
Train Epoch: 1 [620/766 (81%)]	Loss: 1.113803
Train Epoch: 1 [630/766 (82%)]	Loss: 1.140202
Train Epoch: 1 [640/766 (84%)]	Loss: 1.160761
Train Epoch: 1 [650/766 (85%)]	Loss: 1.263138
Train Epoch: 1 [660/766 (86%)]	Loss: 1.176221
Train Epoch: 1 [670/766 (87%)]	Loss: 1.306003
Train Epoch: 1 [680/766 (89%)]	Loss: 1.221295
Train Epoch: 1 [690/766 (90%)]	Loss: 1.152263
Train Epoch: 1 [700/766 (91%)]	Loss: 1.039294
Train Epoch: 1 [710/766 (93%)]	Loss: 1.129845
Train Epoch: 1 [720/766 (94%)]	Loss: 1.092619
Train Epoch: 1 [730/766 (95%)]	Loss: 1.249819
Train Epoch: 1 [740/766 (97%)]	Loss: 1.146910
Train Epoch: 1 [750/766 (98%)]	Loss: 1.193693
Train Epoch: 1 [760/766 (99%)]	Loss: 1.219156
Test Epoch: 1 [0/32 (0%)]	Acc: 0.218750
Test Epoch: 1 [1/32 (3%)]	Acc: 0.343750
Test Epoch: 1 [2/32 (6%)]	Acc: 0.375000
Test Epoch: 1 [3/32 (9%)]	Acc: 0.187500
Test Epoch: 1 [4/32 (12%)]	Acc: 0.343750
Test Epoch: 1 [5/32 (16%)]	Acc: 0.375000
Test Epoch: 1 [6/32 (19%)]	Acc: 0.281250
Test Epoch: 1 [7/32 (22%)]	Acc: 0.250000
Test Epoch: 1 [8/32 (25%)]	Acc: 0.312500
Test Epoch: 1 [9/32 (28%)]	Acc: 0.375000
Test Epoch: 1 [10/32 (31%)]	Acc: 0.343750
Test Epoch: 1 [11/32 (34%)]	Acc: 0.281250
Test Epoch: 1 [12/32 (38%)]	Acc: 0.281250
Test Epoch: 1 [13/32 (41%)]	Acc: 0.406250
Test Epoch: 1 [14/32 (44%)]	Acc: 0.218750
Test Epoch: 1 [15/32 (47%)]	Acc: 0.281250
Test Epoch: 1 [16/32 (50%)]	Acc: 0.343750
Test Epoch: 1 [17/32 (53%)]	Acc: 0.156250
Test Epoch: 1 [18/32 (56%)]	Acc: 0.187500
Test Epoch: 1 [19/32 (59%)]	Acc: 0.312500
Test Epoch: 1 [20/32 (62%)]	Acc: 0.156250
Test Epoch: 1 [21/32 (66%)]	Acc: 0.156250
Test Epoch: 1 [22/32 (69%)]	Acc: 0.156250
Test Epoch: 1 [23/32 (72%)]	Acc: 0.312500
Test Epoch: 1 [24/32 (75%)]	Acc: 0.312500
Test Epoch: 1 [25/32 (78%)]	Acc: 0.281250
Test Epoch: 1 [26/32 (81%)]	Acc: 0.343750
Test Epoch: 1 [27/32 (84%)]	Acc: 0.125000
Test Epoch: 1 [28/32 (88%)]	Acc: 0.250000
Test Epoch: 1 [29/32 (91%)]	Acc: 0.250000
Test Epoch: 1 [30/32 (94%)]	Acc: 0.250000
Test Epoch: 1 [31/32 (97%)]	Acc: 0.375000
Total test acc = 0.274
Train Epoch: 2 [0/766 (0%)]	Loss: 0.916981
Train Epoch: 2 [10/766 (1%)]	Loss: 1.244192
Train Epoch: 2 [20/766 (3%)]	Loss: 1.136918
Train Epoch: 2 [30/766 (4%)]	Loss: 1.019136
Train Epoch: 2 [40/766 (5%)]	Loss: 1.452216
Train Epoch: 2 [50/766 (7%)]	Loss: 1.156905
Train Epoch: 2 [60/766 (8%)]	Loss: 1.207823
Train Epoch: 2 [70/766 (9%)]	Loss: 0.989111
Train Epoch: 2 [80/766 (10%)]	Loss: 0.888812
Train Epoch: 2 [90/766 (12%)]	Loss: 1.165309
Train Epoch: 2 [100/766 (13%)]	Loss: 1.022980
Train Epoch: 2 [110/766 (14%)]	Loss: 1.035037
Train Epoch: 2 [120/766 (16%)]	Loss: 0.995792
Train Epoch: 2 [130/766 (17%)]	Loss: 1.143890
Train Epoch: 2 [140/766 (18%)]	Loss: 0.911665
Train Epoch: 2 [150/766 (20%)]	Loss: 0.864427
Train Epoch: 2 [160/766 (21%)]	Loss: 1.143590
Train Epoch: 2 [170/766 (22%)]	Loss: 1.085069
Train Epoch: 2 [180/766 (23%)]	Loss: 1.176068
Train Epoch: 2 [190/766 (25%)]	Loss: 1.120552
Train Epoch: 2 [200/766 (26%)]	Loss: 1.087845
Train Epoch: 2 [210/766 (27%)]	Loss: 0.992598
Train Epoch: 2 [220/766 (29%)]	Loss: 0.756417
Caught segfault at address 0xb8f4f170, flush log...
stack trace for /usr/bin/python3.7 pid=77488
[New LWP 77530]
[New LWP 77638]
[New LWP 77652]
[New LWP 77653]
[New LWP 77654]
[New LWP 77655]
[New LWP 77656]
[New LWP 77657]
[New LWP 77658]
[New LWP 77659]
[New LWP 77660]
[New LWP 77661]
[New LWP 77662]
[New LWP 77663]
[New LWP 77664]
[New LWP 77665]
[New LWP 77666]
[New LWP 77667]
[New LWP 77668]
[New LWP 77669]
[New LWP 77670]
[New LWP 77671]
[New LWP 77672]
[New LWP 77673]
[New LWP 77674]
[New LWP 77675]
[New LWP 77676]
[New LWP 77677]
[New LWP 77678]
[New LWP 77679]
[New LWP 77680]
[New LWP 77681]
[New LWP 77682]
[New LWP 77683]
[New LWP 77684]
[New LWP 77685]
[New LWP 77686]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f35e93926c2 in __GI___waitpid (pid=78009, stat_loc=0x0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
[Current thread is 1 (Thread 0x7f35e98b7740 (LWP 77488))]
#0  0x00007f35e93926c2 in __GI___waitpid (pid=78009, stat_loc=0x0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f35e47637c2 in jittor::print_trace() () from /root/.cache/jittor/default/g++/jit_utils_core.so
#2  0x00007f35e475cf45 in jittor::segfault_sigaction(int, siginfo_t*, void*) () from /root/.cache/jittor/default/g++/jit_utils_core.so
#3  <signal handler called>
#4  0x00007f35df3c9ec6 in jittor::CachingBlockPool::get_occupied(unsigned long) () from /root/.cache/jittor/default/g++/jittor_core.so
#5  0x00007f35df3cb4a7 in jittor::SFRLAllocator::free(void*, unsigned long, unsigned long const&) () from /root/.cache/jittor/default/g++/jittor_core.so
#6  0x00007f35df4190a3 in jittor::ArrayOp::ArrayOp(jittor::ArrayArgs&&) () from /root/.cache/jittor/default/g++/jittor_core.so
#7  0x00007f35df36aee0 in jittor::jit_op_maker::make_array_(jittor::ArrayArgs&&) () from /root/.cache/jittor/default/g++/jittor_core.so
#8  0x00007f35df36b114 in jittor::jit_op_maker::array_(jittor::ArrayArgs&&) () from /root/.cache/jittor/default/g++/jittor_core.so
#9  0x00007f35df3b83be in std::enable_if<std::is_same<jittor::VarHolder*, jittor::VarHolder*>::value, jittor::VarHolder*>::type jittor::from_py_object<jittor::VarHolder*>(_object*, std::unique_ptr<jittor::VarHolder, std::default_delete<jittor::VarHolder> >&) () from /root/.cache/jittor/default/g++/jittor_core.so
Segfault, exit
```
I met this Segment Fault when I run the Cifar10 datasets on CNN, the code of my modle is:

```
import jittor as jt
from jittor import nn, Module
import numpy as np
import sys, os
import random
import math
from jittor import init


class CIFAR10_FAST_MODEL(nn.Module):
    def __init__(self):
        super(CIFAR10_FAST_MODEL, self).__init__()
        self.conv1_1 = nn.Conv(3, 32, kernel_size=3, padding=1)
        self.conv1_2 = nn.Conv(32, 32, kernel_size=3, padding=1)
        self.pool1 = nn.Pool(kernel_size=2, stride=2, op='maximum')
        self.dropout1 = nn.Dropout(p=0.2)
        self.bn32 = nn.BatchNorm(32)
        self.conv2_1 = nn.Conv(32, 64, kernel_size=3, padding=1)
        self.conv2_2 = nn.Conv(64, 64, kernel_size=3, padding=1)
        self.pool2 = nn.Pool(kernel_size=2, stride=2, op='maximum')
        self.dropout2 = nn.Dropout(p=0.3)
        self.bn64 = nn.BatchNorm(64)
        self.conv3_1 = nn.Conv(64, 128, kernel_size=3, padding=1)
        self.conv3_2 = nn.Conv(128, 128, kernel_size=3, padding=1)
        self.pool3 = nn.Pool(kernel_size=2, stride=2, op='maximum')
        self.dropout3 = nn.Dropout(p=0.4)
        self.bn128 = nn.BatchNorm(128)
        self.relu = nn.Relu()
        self.fc1 = nn.Linear (2048, 10)


    def execute(self, image):
        out = nn.relu(self.conv1_1(image))
        out = self.bn32(out)
        out = nn.relu(self.conv1_2(out))
        out = self.bn32(out)
        out = self.pool1(out)
        out = self.dropout1(out)
        out = nn.relu(self.conv2_1(out))
        out = self.bn64(out)
        out = nn.relu(self.conv2_2(out))
        out = self.bn64(out)
        out = self.pool2(out)
        out = self.dropout2(out)
        out = nn.relu(self.conv3_1(out))
        out = self.bn128(out)
        out = nn.relu(self.conv3_2(out))
        out = self.bn128(out)
        out = self.pool3(out)
        out = self.dropout3(out)

        x = jt.reshape(out, [out.shape[0], -1])
        # print("x's shape: ", np.shape(x))
        x = self.fc1(x)
        return x
```

**Comment by Jittor** [comment]
Thanks for your feedback, It is hard for me to determine the bug, could you please give us more log, and your training script for us to reproduce this error?

**Comment by Unrealluver** [comment]
> Thanks for your feedback, It is hard for me to determine the bug, could you please give us more log, and your training script for us to reproduce this error?

https://github.com/Unrealluver/CV-Projects here is my repo, in the project4CNN Part, I used Jittor. Two error has been found now: 
1. If I  run the model in the model.py over 17 epochs with CPU, the error above will occur.
2. If I use the nn.batchnorm rather than the nn.BatchNorm, the CPU will be occupied by the python interpreter right now, I could even not run just 1 epoch entirely.
