### ISSUE TITLE
安装成功，使用时错误

### ISSUE THREAD

**Issue by labAxiaoming** [Jittor/jittor#49]
你好请教一下：
（1）安装 python3.7-dev，
sudo apt install python3.7-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3.7-dev
E: Couldn't find any package by glob 'python3.7-dev'
E: Couldn't find any package by regex 'python3.7-dev'

（2）不管1， 直接能安装成功
python3.7 -m pip install git+https://github.com/Jittor/jittor.git成功后
import jittor或者python3.7 -m jittor.test.test_example都出现
[i 0402 21:49:51.393790 80 __init__.py:195] Found g++(5.4.0) at /usr/bin/g++.
py3_config_path /usr/bin/python33-config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/python3.7/lib/python3.7/site-packages/jittor/__init__.py", line 10, in <module>
    from . import compiler
  File "/opt/python3.7/lib/python3.7/site-packages/jittor/compiler.py", line 782, in <module>
    assert os.path.isfile(py3_config_path)
AssertionError
import jittor，py3_config_path打印出来是 /usr/bin/python33-config，
python3.7 -m jittor.test.test_example，py3_config_path打印出来是/usr/bin/python3.73-config
 /usr/bin/里面没有python33-config，python3.73-config

**Comment by cjld** [comment]
您好，请问您使用的是ubuntu16.04吗，python3.7-dev需要使用私有源安装，这里有一个参考链接，似乎和您碰到了一样的问题：
https://www.digitalocean.com/community/questions/unable-to-install-pyhton-3-7-version-on-ubuntu-16-04-error-couldn-t-find-any-package-by-regex-python3-7
