### ISSUE TITLE
Centos安装失败

### ISSUE THREAD

**Issue by krauwu** [Jittor/jittor#569]
当运行 jittor.test.test_example, 报g++: fatal error: too many input files； 
运行环境：g++，gcc版本=9.3， cuda=11.8
系统版本：Linux VM-160-14-tencentos 5.4.119-19.0009.28  x86_64 x86_64 x86_64 GNU/Linux

[i 0710 16:31:08.505239 80 compiler.py:956] Jittor(1.3.9.10) src: /data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor
[i 0710 16:31:08.507646 80 compiler.py:957] g++ at g++(9.3.0)
[i 0710 16:31:08.507728 80 compiler.py:958] cache_path: /root/.cache/jittor/jt1.3.9/g++9.3.0/py3.7.16/Linux-5.4.119-xf5/IntelRXeonRPlaxb9/fea3/default
[i 0710 16:31:08.510648 80 compiler.py:901] Found nvcc(11.8.89) at /usr/local/cuda/bin/nvcc
[i 0710 16:31:08.528045 80 __init__.py:412] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0710 16:31:08.530565 80 __init__.py:412] Found addr2line(2.1) at /usr/bin/addr2line.
[i 0710 16:31:10.659895 80 compiler.py:1011] cuda key:cu11.8.89_sm_90
g++: fatal error: too many input files
compilation terminated.
Traceback (most recent call last):
  File "/data1/miniconda3/envs/songbur/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/data1/miniconda3/envs/songbur/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/compiler.py", line 1190, in <module>
    check_cache_compile()
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/compiler.py", line 885, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "g++" "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src/utils/cache_compile.cc" "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src/utils/log.cc" "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src/utils/tracer.cc" "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src/utils/jit_utils.cc" "/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/data1/miniconda3/envs/songbur/lib/python3.7/site-packages/jittor/src" -I/data1/miniconda3/envs/songbur/include/python3.7m -I/data1/miniconda3/envs/songbur/include/python3.7m  -O2   -o "/root/.cache/jittor/jt1.3.9/g++9.3.0/py3.7.16/Linux-5.4.119-xf5/IntelRXeonRPlaxb9/fea3/default/jit_utils_core.cpython-37m-x86_64-linux-gnu.so"

**Comment by krauwu** [comment]
g++版本需要稳定在9.4
