### ISSUE TITLE
编辑报错void (__cdecl jittor::Node::* )(void)

### ISSUE THREAD

**Issue by qian-yins** [Jittor/jittor#624]
## Describe the bug
我在根据windows下源代码安装提示操作时，在运行 python -m jittor.test.test_core报出一下错误：C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(468): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'

## Full Log

(Jittor) C:\Users\somebody>python -m jittor.test.test_core
[i 1218 10:12:23.509000 00 compiler.py:956] Jittor(1.3.9.13) src: d:\mywork2\jittor\python\jittor
[i 1218 10:12:23.553000 00 compiler.py:957] cl at C:\Users\somebody\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1218 10:12:23.553000 00 compiler.py:958] cache_path: C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master
[i 1218 10:12:23.916000 00 install_cuda.py:96] cuda_driver_version: [12, 6, 0]
[i 1218 10:12:24.006000 00 __init__.py:412] Found C:\Users\somebody\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at C:\Users\somebody\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 1218 10:12:24.053000 00 compiler.py:1013] cuda key:cu11.2.67
[i 1218 10:12:24.066000 00 __init__.py:227] Total mem: 31.68GB, using 10 procs for compiling.
data.cc
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(418): warning C4273: 'jittor::tflag_count': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(88): note: see previous definition of 'tflag_count'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(418): warning C4273: 'jittor::nt': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(18): note: see previous definition of 'nt'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(419): warning C4273: 'jittor::lived_nodes': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(15): note: see previous definition of 'lived_nodes'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(419): warning C4273: 'jittor::lived_nodes_id': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(16): note: see previous definition of 'lived_nodes_id'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(419): warning C4273: 'jittor::total_node': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(17): note: see previous definition of 'total_node'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(419): warning C4273: 'jittor::free_buffer': inconsistent dll linkage
d:\mywork2\jittor\python\jittor\src\node.h(19): note: see previous definition of 'free_buffer'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(421): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(422): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(422): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(422): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(422): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(423): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(423): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(426): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(426): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(426): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(426): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(427): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(427): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(439): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(439): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(441): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(441): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(443): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(443): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(445): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(445): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(446): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(446): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(455): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(455): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(457): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(457): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(457): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(457): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(458): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(458): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(458): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(458): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(459): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(459): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(460): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(460): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(460): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(460): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(462): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(462): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(464): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(464): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(465): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(465): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(466): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(466): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(467): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(467): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(468): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(468): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(469): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(469): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(470): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(470): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(473): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(473): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(474): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(474): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(474): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(474): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(479): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(479): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(480): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(480): note: There is no context in which this conversion is possible
C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(558): warning C4551: function call missing argument list
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "d:\mywork2\jittor\python\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "d:\mywork2\jittor\python\jittor\compiler.py", line 1348, in <module>
    run_cmd(fix_cl_flags(f"\"{cc_path}\" {dflags} -include \"{vdp}\" \"{data_s_path}\" -c -o \"{data_o_path}\""))
  File "d:\mywork2\jittor\python\jittor_utils\__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "C:\Users\somebody\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe"    -std:c++17         -EHa -MD -utf-8  -nologo -I"C:\Users\somebody\.cache\jittor\msvc\VC\include" -I"C:\Users\somebody\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\somebody\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\somebody\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"d:\mywork2\jittor\python\jittor\src" -I"d:\.conda\envs\jittor\include" -DHAS_CUDA -DIS_CUDA -I"C:\Users\somebody\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"d:\mywork2\jittor\python\jittor\extern\cuda\inc"   -I"C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67"  -O2  -FI "d:\mywork2\jittor\python\jittor\src\utils\vdp" "C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc" -c -Fo: "C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.obj" -link -LIBPATH:"d:\.conda\envs\jittor\libs" python311.lib -LIBPATH:"C:\Users\somebody\.cache\jittor\msvc\VC\lib" -LIBPATH:"C:\Users\somebody\.cache\jittor\msvc\win10_kits\lib\um\x64" -LIBPATH:"C:\Users\somebody\.cache\jittor\msvc\win10_kits\lib\ucrt\x64" cudart.lib -LIBPATH:"C:\Users\somebody\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\lib\x64" -LIBPATH:"C:\Users\somebody\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin" -LIBPATH:"C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67" -LIBPATH:"C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master"
## Minimal Reproduce

C:\Users\somebody\.cache\jittor\jt1.3.9\cl\py3.11.10\Windows-10-10.x8c\13thGenIntelRCx11\2d53\master\cu11.2.67\data.cc(468): error C2440: 'type cast': cannot convert from 'void (__cdecl jittor::Node::* )(void)' to 'void (__cdecl *)(jittor::Node *)'

## Expected behavior
解决

If you are submitting an issue for the first time, please refer to [our guideline](https://github.com/Jittor/jittor/issues/238)

**Comment by ZuoguanPikachu** [comment]
可以尝试回退到1.3.7.10版本

**Comment by zhaozk23** [comment]
请问最后这个问题是如何解决的？

**Comment by nanxi666** [comment]
可以尝试低版本jittor，比如
pip install jittor==1.3.8.1
