### ISSUE TITLE
ERROR: Package 'jittor' requires a different Python: 2.7.17 not in '>=3.7'

### ISSUE THREAD

**Issue by resplendent-star** [Jittor/jittor#7]
hello,after I execute the comand in  ubuntu 18.04

sudo pip install ./jittor 

and get error :ERROR: Package 'jittor' requires a different Python: 2.7.17 not in '>=3.7'

**Comment by cxjyxxme** [comment]
First you need to install python3.7 and you can run
`python3.7 -m pip install ./jittor`

**Comment by resplendent-star** [comment]
hi,after  execute this command  : sudo apt install python3.7 

and then execute python3.7 -m pip install ./jittor,
then I get these errors:

python3.7 -m pip install ./jittor
Processing ./jittor
Collecting astunparse (from jittor==1.0.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py", line 303, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py", line 187, in proxy_manager_for
    **proxy_kwargs
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py", line 44, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
pip._vendor.requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

**Comment by cxjyxxme** [comment]
Hello，if you cannot install dependencies from pip, please check the network environment.

**Comment by resplendent-star** [comment]
> 您好，如果您无法通过pip安装依赖项，请检查网络环境。

hello,thanks for reply,I am online,but actually have problems when  I  try  to  use pip to instal  something,so  I chang the source to  aliyun source  in order to install numpy  etc,
