### ISSUE TITLE
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by qianzhang613** [Jittor/jittor#70]
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

how to  jittor support cuda10.1 ? 

thanks

**Comment by cjld** [comment]
Thanks for your feedback, could you please provide the whole error log of Jittor?

**Comment by qianzhang613** [comment]
python3.7 -m jittor.test.test_example
[i 0427 21:51:44.942432 68 __init__.py:203] Found g++(7.5.0) at /usr/bin/g++.
[i 0427 21:51:44.960738 56 __init__.py:203] Found /usr/local/cuda/bin/nvcc(10.1.243) at /usr/local/cuda/bin/nvcc.
[i 0427 21:51:45.067512 56 __init__.py:203] Found gdb(8.1.0) at /usr/bin/gdb.
[i 0427 21:51:45.077206 56 __init__.py:203] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0427 21:51:45.162379 56 compiler.py:848] pybind_include: -I/usr/include/python3.7m -I/usr/local/lib/python3.7/dist-packages/pybind11/include
[i 0427 21:51:45.172447 56 compiler.py:850] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 12, in <module>
    from . import compiler
  File "/usr/local/lib/python3.7/dist-packages/jittor/compiler.py", line 958, in <module>
    import jittor_core as core
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.7/dist-packages/jittor/__init__.py", line 12, in <module>
    from . import compiler
  File "/usr/local/lib/python3.7/dist-packages/jittor/compiler.py", line 958, in <module>
    import jittor_core as core
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
➜  docker_images git:(master)

**Comment by qianzhang613** [comment]
my cuda is:
sudo apt-get install --no-install-recommends \
    cuda-10-1 \
    libcudnn7=7.6.4.38-1+cuda10.1  \
    libcudnn7-dev=7.6.4.38-1+cuda10.1

**Comment by cjld** [comment]
could you please provide outputs of the command: `ls -la /usr/local/cuda/lib64`. Those information can help us diagnose your problem.

**Comment by qianzhang613** [comment]
➜  ~ ls -la /usr/local/cuda/lib64
lrwxrwxrwx 1 root root 24 Aug 10  2019 /usr/local/cuda/lib64 -> targets/x86_64-linux/lib
➜  ~ ls /usr/local/cuda/lib64    

libaccinj64.so                libcuinj64.so.10.1           liblapack_static.a        libnppidei.so             libnppist.so.10.2.0.243  libnvjpeg.so
libaccinj64.so.10.1           libcuinj64.so.10.1.243       libmetis_static.a         libnppidei.so.10          libnppist_static.a       libnvjpeg.so.10
libaccinj64.so.10.1.243       libculibos.a                 libnppc.so                libnppidei.so.10.2.0.243  libnppisu.so             libnvjpeg.so.10.3.0.243
libcudadevrt.a                libcurand.so                 libnppc.so.10             libnppidei_static.a       libnppisu.so.10          libnvjpeg_static.a
libcudart.so                  libcurand.so.10              libnppc.so.10.2.0.243     libnppif.so               libnppisu.so.10.2.0.243  libnvrtc-builtins.so
libcudart.so.10.1             libcurand.so.10.1.1.243      libnppc_static.a          libnppif.so.10            libnppisu_static.a       libnvrtc-builtins.so.10.1
libcudart.so.10.1.243         libcurand_static.a           libnppial.so              libnppif.so.10.2.0.243    libnppitc.so             libnvrtc-builtins.so.10.1.243
libcudart_static.a            libcusolverMg.so             libnppial.so.10           libnppif_static.a         libnppitc.so.10          libnvrtc.so
libcufft.so                   libcusolverMg.so.10          libnppial.so.10.2.0.243   libnppig.so               libnppitc.so.10.2.0.243  libnvrtc.so.10.1
libcufft.so.10                libcusolverMg.so.10.2.0.243  libnppial_static.a        libnppig.so.10            libnppitc_static.a       libnvrtc.so.10.1.243
libcufft.so.10.1.1.243        libcusolver.so               libnppicc.so              libnppig.so.10.2.0.243    libnpps.so               libnvToolsExt.so
libcufft_static.a             libcusolver.so.10            libnppicc.so.10           libnppig_static.a         libnpps.so.10            libnvToolsExt.so.1
libcufft_static_nocallback.a  libcusolver.so.10.2.0.243    libnppicc.so.10.2.0.243   libnppim.so               libnpps.so.10.2.0.243    libnvToolsExt.so.1.0.0
libcufftw.so                  libcusolver_static.a         libnppicc_static.a        libnppim.so.10            libnpps_static.a         libOpenCL.so
libcufftw.so.10               libcusparse.so               libnppicom.so             libnppim.so.10.2.0.243    libnvgraph.so            libOpenCL.so.1
libcufftw.so.10.1.1.243       libcusparse.so.10            libnppicom.so.10          libnppim_static.a         libnvgraph.so.10         libOpenCL.so.1.1
libcufftw_static.a            libcusparse.so.10.3.0.243    libnppicom.so.10.2.0.243  libnppist.so              libnvgraph.so.10.1.243   stubs
libcuinj64.so
