### ISSUE TITLE
安装运行jittor.test.test_example失败

### ISSUE THREAD

**Issue by mepwang** [Jittor/jittor#87]
OS：Ubuntu 20.04
安装过程：
1、用python -m venv jittorenv创建虚拟环境（python3.8）
2、source jittorenv/bin/activate
3、pip install git+https://github.com/Jittor/jittor.git
前面的过程都没有错误
4、python -m jittor.test.test_example
[i 0522 07:38:11.469688 64 __init__.py:211] Found g++(9.3.0) at /usr/bin/g++.
[i 0522 07:38:11.475355 64 lock.py:58] Create lock file: /home/mep/.cache/jittor/default/jittor.lock
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/mep/ds/jittor/jittorenv/lib/python3.8/site-packages/jittor/__init__.py", line 12, in <module>
    from . import compiler
  File "/home/mep/ds/jittor/jittorenv/lib/python3.8/site-packages/jittor/compiler.py", line 823, in <module>
    assert os.path.isfile(py3_config_path)
AssertionError

**Comment by mepwang** [comment]
找到原因了，jittor试图寻找python3-config，但python虚拟运行环境中没有这个可执行文件。
也就是说，jittor现阶段还不支持安装到python虚拟运行环境，好像是这样吧？

**Comment by cjld** [comment]
你好，感谢你的反馈，运行jittor需要安装python3.7-dev 或者python3.8-dev, `apt install python3.8-dev`，装好这个以后应该是可以在虚拟环境里运行的

**Comment by cjld** [comment]
如果后续有出现任何问题也欢迎通过这个issue 反馈

**Comment by mepwang** [comment]
python3-config位于系统目录下/usr/bin/python3-config，python虚拟运行环境中没有提供python3-config，这个问题和python3-dev安装包没有关系

**Comment by cjld** [comment]
了解了，感谢您的反馈，我们将尽快修复这个问题
